In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow.keras
from VectorNormalizer import VectorNormalizer

2022-03-17 15:10:10.222039: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-03-17 15:10:10.222131: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [2]:
df = pd.read_csv('_data.csv')

In [3]:
df.drop(columns=['timestep_time'], axis=1, inplace=True)

In [4]:
df.describe().T

count       mean       std  min    25%    50%    75%    max
vehicle_0   1369.0  13.304617  0.730812  0.0  13.01  13.34  13.68  14.00
vehicle_1   1369.0   8.840175  0.489463  0.0   8.53   8.85   9.17   9.52
vehicle_2   1369.0  14.572922  0.798959  0.0  14.29  14.63  14.94  15.27
vehicle_3   1369.0  13.307414  0.700379  0.0  13.01  13.36  13.67  14.00
vehicle_4   1369.0  11.320131  0.602395  0.0  11.02  11.34  11.67  12.00
vehicle_5   1369.0   6.515530  0.443259  0.0   6.20   6.52   6.85   7.18
vehicle_6   1369.0  11.320497  0.605771  0.0  11.02  11.34  11.68  12.00
vehicle_7   1369.0   4.696143  0.400734  0.0   4.38   4.70   5.03   5.35
vehicle_8   1369.0   3.460131  0.380911  0.0   3.14   3.46   3.77   4.12
vehicle_9   1369.0   3.428356  0.388740  0.0   3.11   3.42   3.77   4.08
vehicle_10  1369.0  12.319277  0.677380  0.0  12.03  12.35  12.69  13.00
vehicle_11  1369.0  14.688671  0.811304  0.0  14.41  14.75  15.05  15.38
vehicle_12  1369.0  11.339211  0.632542  0.0  11.04  11.38  11.70  12.00
vehicle_13  1369.0  12.320979  0.673965  0.0  12.01  12.35  12.69  13.00
vehicle_14  1369.0   9.781132  0.546465  0.0   9.46   9.81  10.14  10.45
vehicle_15  1369.0  13.317516  0.706316  0.0  13.03  13.35  13.68  14.00
vehicle_16  1369.0  11.479912  0.596174  0.0  11.19  11.52  11.83  12.13
vehicle_17  1369.0  12.652761  0.674286  0.0  12.37  12.68  13.02  13.33
vehicle_18  1369.0   8.010804  0.472543  0.0   7.69   8.01   8.36   8.68
vehicle_19  1369.0  13.324083  0.749694  0.0  13.04  13.36  13.69  14.00

In [7]:
df = df.iloc[4:, :]

In [8]:
pd.set_option('display.max_rows', len(range(1368)))
pd.reset_option('display.max_rows')

In [10]:
df

vehicle_0  vehicle_1  vehicle_2  vehicle_3  vehicle_4  vehicle_5  \
5          9.45       8.63       8.92      10.40       9.69       6.62   
6         11.99       8.29      11.01      12.49      11.08       7.00   
7         13.03       9.13      12.75      12.84      11.06       5.94   
8         13.68       8.51      14.76      13.16      10.79       5.93   
9         13.29       8.55      14.83      12.88      11.15       6.55   
...         ...        ...        ...        ...        ...        ...   
1364      13.64       9.47      14.64      13.89      10.99       6.90   
1365      13.53       8.26      15.24      13.15      11.13       6.07   
1366      13.09       9.41      14.78      13.83      11.05       5.89   
1367      13.55       9.02      14.95      12.93      11.64       6.72   
1368      13.78       8.78      14.28      13.35      10.85       6.51   

      vehicle_6  vehicle_7  vehicle_8  vehicle_9  vehicle_10  vehicle_11  \
5         10.40       5.18       4.00       3.03        8.37        9.61   
6         11.75       4.99       4.03       3.28       10.23       11.33   
7         10.87       4.37       3.25       3.48       12.49       12.73   
8         11.38       4.47       4.00       3.37       12.68       15.24   
9         11.83       4.37       3.38       4.01       12.63       15.32   
...         ...        ...        ...        ...         ...         ...   
1364      11.63       4.43       2.91       3.42       12.10       14.19   
1365      10.81       4.87       3.92       3.09       11.89       14.27   
1366      11.36       5.05       3.13       3.16       12.07       15.25   
1367      11.64       4.41       3.51       3.72       12.91       15.34   
1368      11.75       4.68       3.81       3.69       11.93       14.94   

      vehicle_12  vehicle_13  vehicle_14  vehicle_15  vehicle_16  vehicle_17  \
5           9.39        9.35        9.24        9.65       10.92        9.82   
6          11.15       11.87        9.62       11.06       11.84       12.16   
7          11.17       11.84        9.29       13.12       11.06       12.44   
8          11.27       12.05        9.78       12.95       11.30       12.74   
9          11.85       12.60       10.01       13.99       11.62       12.49   
...          ...         ...         ...         ...         ...         ...   
1364       11.59       12.49        9.92       13.81       11.24       12.16   
1365       11.42       12.26        9.37       13.90       11.79       12.64   
1366       11.88       12.37       10.37       12.78       11.46       12.72   
1367       10.76       12.94        9.67       13.33       10.85       13.20   
1368       10.85       12.56        9.51       13.04       11.16       12.39   

      vehicle_18  vehicle_19  
5           7.76        8.93  
6           8.35       11.34  
7           7.56       13.83  
8           8.29       13.83  
9           8.62       12.90  
...          ...         ...  
1364        7.94       13.15  
1365        8.40       12.82  
1366        7.50       13.43  
1367        7.85       12.93  
1368        8.19       12.79  

[1364 rows x 20 columns]

In [11]:
scaler = VectorNormalizer()
scaler.fit(df)
df_scale_speed = scaler.transform(df)

In [12]:
df_scale_speed

0         1         2         3         4         5         6   \
0     0.242264  0.221242  0.228677  0.266619  0.248417  0.169713  0.266619   
1     0.264756  0.183055  0.243116  0.275797  0.244662  0.154570  0.259456   
2     0.273783  0.191837  0.267899  0.269790  0.232390  0.124810  0.228397   
3     0.275948  0.171661  0.297734  0.265459  0.217652  0.119618  0.229553   
4     0.265250  0.170646  0.295986  0.257067  0.222538  0.130729  0.236110   
...        ...       ...       ...       ...       ...       ...       ...   
1359  0.274796  0.190786  0.294942  0.279833  0.221408  0.139010  0.234302   
1360  0.274860  0.167801  0.309599  0.267141  0.226105  0.123311  0.219604   
1361  0.263185  0.189196  0.297164  0.278064  0.222169  0.118423  0.228402   
1362  0.271295  0.180596  0.299325  0.258881  0.233053  0.134546  0.233053   
1363  0.280843  0.178941  0.291034  0.272080  0.221128  0.132677  0.239471   

            7         8         9         10        11        12        13  \
0     0.132797  0.102546  0.077678  0.214577  0.246366  0.240726  0.239701   
1     0.110186  0.088988  0.072427  0.225893  0.250182  0.246208  0.262106   
2     0.091821  0.068288  0.073121  0.262436  0.267479  0.234701  0.248779   
3     0.090167  0.080687  0.067978  0.255777  0.307416  0.227334  0.243068   
4     0.087219  0.067460  0.080034  0.252077  0.305766  0.236509  0.251478   
...        ...       ...       ...       ...       ...       ...       ...   
1359  0.089248  0.058626  0.068900  0.243771  0.285876  0.233496  0.251628   
1360  0.098933  0.079634  0.062773  0.241544  0.289893  0.231996  0.249060   
1361  0.101534  0.062931  0.063534  0.242677  0.306614  0.238857  0.248709   
1362  0.088296  0.070276  0.074481  0.258481  0.307134  0.215434  0.259082   
1363  0.095381  0.077650  0.075204  0.243139  0.304485  0.221128  0.255979   

            14        15        16        17        18        19  
0     0.236881  0.247392  0.279950  0.251750  0.198939  0.228933  
1     0.212423  0.244220  0.261444  0.268510  0.184380  0.250403  
2     0.195199  0.275674  0.232390  0.261386  0.158849  0.290592  
3     0.197279  0.261223  0.227940  0.256987  0.167223  0.278974  
4     0.199785  0.279221  0.231919  0.249283  0.172043  0.257466  
...        ...       ...       ...       ...       ...       ...  
1359  0.199852  0.278221  0.226445  0.244979  0.159962  0.264924  
1360  0.190350  0.282377  0.239512  0.256780  0.170645  0.260437  
1361  0.208497  0.256952  0.230413  0.255746  0.150794  0.270021  
1362  0.193610  0.266890  0.217236  0.264287  0.157171  0.258881  
1363  0.193819  0.265762  0.227446  0.252514  0.166916  0.260667  

[1364 rows x 20 columns]

## Hardcode shit

In [13]:
car_1 = df_scale_speed.loc[:, 0]
car_2 = df_scale_speed.loc[:, 1]
car_3 = df_scale_speed.loc[:, 2]
car_4 = df_scale_speed.loc[:, 3]
car_5 = df_scale_speed.loc[:, 4]
car_6 = df_scale_speed.loc[:, 5]
car_7 = df_scale_speed.loc[:, 6]
car_8 = df_scale_speed.loc[:, 7]
car_9 = df_scale_speed.loc[:, 8]
car_10 = df_scale_speed.loc[:, 9]
car_11 = df_scale_speed.loc[:, 10]
car_12 = df_scale_speed.loc[:, 11]
car_13 = df_scale_speed.loc[:, 12]
car_14 = df_scale_speed.loc[:, 13]
car_15 = df_scale_speed.loc[:, 14]
car_16 = df_scale_speed.loc[:, 15]
car_17 = df_scale_speed.loc[:, 16]
car_18 = df_scale_speed.loc[:, 17]
car_19 = df_scale_speed.loc[:, 18]
car_20 = df_scale_speed.loc[:, 19]

In [14]:
# splitting train - test data

train_car1 = car_1.iloc[:1200]
test_car1 = car_1.iloc[1200:]

train_car2 = car_2.iloc[:1200]
test_car2 = car_2.iloc[1200:]

train_car3 = car_3.iloc[:1200]
test_car3 = car_3.iloc[1200:]

train_car4 = car_4.iloc[:1200]
test_car4 = car_4.iloc[1200:]

train_car5 = car_5.iloc[:1200]
test_car5 = car_5.iloc[1200:]

train_car6 = car_6.iloc[:1200]
test_car6 = car_6.iloc[1200:]

train_car7 = car_7.iloc[:1200]
test_car7 = car_7.iloc[1200:]

train_car8 = car_8.iloc[:1200]
test_car8 = car_8.iloc[1200:]

train_car9 = car_9.iloc[:1200]
test_car9 = car_9.iloc[1200:]

train_car10 = car_10.iloc[:1200]
test_car10 = car_10.iloc[1200:]

train_car11 = car_11.iloc[:1200]
test_car11 = car_11.iloc[1200:]

train_car12 = car_12.iloc[:1200]
test_car12 = car_12.iloc[1200:]

train_car13 = car_13.iloc[:1200]
test_car13= car_13.iloc[1200:]

train_car14 = car_14.iloc[:1200]
test_car14 = car_14.iloc[1200:]

train_car14 = car_14.iloc[:1200]
test_car14 = car_14.iloc[1200:]

train_car15 = car_15.iloc[:1200]
test_car15 = car_15.iloc[1200:]

train_car16 = car_16.iloc[:1200]
test_car16 = car_16.iloc[1200:]

train_car17 = car_17.iloc[:1200]
test_car17 = car_17.iloc[1200:]

train_car18 = car_18.iloc[:1200]
test_car18 = car_18.iloc[1200:]

train_car19 = car_19.iloc[:1200]
test_car19 = car_19.iloc[1200:]

train_car20 = car_20.iloc[:1200]
test_car20 = car_20.iloc[1200:]

In [15]:
from utils import create_dataset

In [16]:
TIME_STEPS = 4

train_features_speed1, train_labels_speed1 = create_dataset(train_car1.to_numpy(), TIME_STEPS)
test_features_speed1, test_labels_speed1 = create_dataset(test_car1.to_numpy(), TIME_STEPS)

train_features_speed2, train_labels_speed2 = create_dataset(train_car2.to_numpy(), TIME_STEPS)
test_features_speed2, test_labels_speed2 = create_dataset(test_car2.to_numpy(), TIME_STEPS)

train_features_speed3, train_labels_speed3 = create_dataset(train_car3.to_numpy(), TIME_STEPS)
test_features_speed3, test_labels_speed3 = create_dataset(test_car3.to_numpy(), TIME_STEPS)

train_features_speed4, train_labels_speed4 = create_dataset(train_car4.to_numpy(), TIME_STEPS)
test_features_speed4, test_labels_speed4 = create_dataset(test_car4.to_numpy(), TIME_STEPS)

train_features_speed5, train_labels_speed5 = create_dataset(train_car5.to_numpy(), TIME_STEPS)
test_features_speed5, test_labels_speed5 = create_dataset(test_car5.to_numpy(), TIME_STEPS)

train_features_speed6, train_labels_speed6 = create_dataset(train_car6.to_numpy(), TIME_STEPS)
test_features_speed6, test_labels_speed6 = create_dataset(test_car6.to_numpy(), TIME_STEPS)

train_features_speed7, train_labels_speed7 = create_dataset(train_car7.to_numpy(), TIME_STEPS)
test_features_speed7, test_labels_speed7 = create_dataset(test_car7.to_numpy(), TIME_STEPS)

train_features_speed8, train_labels_speed8 = create_dataset(train_car8.to_numpy(), TIME_STEPS)
test_features_speed8, test_labels_speed8 = create_dataset(test_car8.to_numpy(), TIME_STEPS)

train_features_speed9, train_labels_speed9 = create_dataset(train_car9.to_numpy(), TIME_STEPS)
test_features_speed9, test_labels_speed9 = create_dataset(test_car9.to_numpy(), TIME_STEPS)

train_features_speed10, train_labels_speed10 = create_dataset(train_car10.to_numpy(), TIME_STEPS)
test_features_speed10, test_labels_speed10 = create_dataset(test_car10.to_numpy(), TIME_STEPS)

train_features_speed11, train_labels_speed11 = create_dataset(train_car11.to_numpy(), TIME_STEPS)
test_features_speed11, test_labels_speed11 = create_dataset(test_car11.to_numpy(), TIME_STEPS)

train_features_speed12, train_labels_speed12 = create_dataset(train_car12.to_numpy(), TIME_STEPS)
test_features_speed12, test_labels_speed12 = create_dataset(test_car12.to_numpy(), TIME_STEPS)

train_features_speed13, train_labels_speed13 = create_dataset(train_car13.to_numpy(), TIME_STEPS)
test_features_speed13, test_labels_speed13 = create_dataset(test_car13.to_numpy(), TIME_STEPS)

train_features_speed14, train_labels_speed14 = create_dataset(train_car14.to_numpy(), TIME_STEPS)
test_features_speed14, test_labels_speed14 = create_dataset(test_car14.to_numpy(), TIME_STEPS)

train_features_speed15, train_labels_speed15 = create_dataset(train_car15.to_numpy(), TIME_STEPS)
test_features_speed15, test_labels_speed15 = create_dataset(test_car15.to_numpy(), TIME_STEPS)

train_features_speed16, train_labels_speed16 = create_dataset(train_car16.to_numpy(), TIME_STEPS)
test_features_speed16, test_labels_speed16 = create_dataset(test_car16.to_numpy(), TIME_STEPS)

train_features_speed17, train_labels_speed17 = create_dataset(train_car17.to_numpy(), TIME_STEPS)
test_features_speed17, test_labels_speed17 = create_dataset(test_car17.to_numpy(), TIME_STEPS)

train_features_speed18, train_labels_speed18 = create_dataset(train_car18.to_numpy(), TIME_STEPS)
test_features_speed18, test_labels_speed18 = create_dataset(test_car18.to_numpy(), TIME_STEPS)

train_features_speed19, train_labels_speed19 = create_dataset(train_car19.to_numpy(), TIME_STEPS)
test_features_speed19, test_labels_speed19 = create_dataset(test_car19.to_numpy(), TIME_STEPS)

train_features_speed20, train_labels_speed20 = create_dataset(train_car20.to_numpy(), TIME_STEPS)
test_features_speed20, test_labels_speed20 = create_dataset(test_car20.to_numpy(), TIME_STEPS)

In [17]:
print(train_features_speed20.shape)
print(test_features_speed20.shape)
print(train_labels_speed20.shape)
print(test_labels_speed20.shape)

(1196, 4)
(160, 4)
(1196,)
(160,)


In [18]:
train_features_speed1 = train_features_speed1.reshape(1196, 4,1)
test_features_speed1 = test_features_speed1.reshape(160, 4,1)

train_features_speed2 = train_features_speed2.reshape(1196, 4,1)
test_features_speed2 = test_features_speed2.reshape(160, 4,1)

train_features_speed3 = train_features_speed3.reshape(1196, 4,1)
test_features_speed3 = test_features_speed3.reshape(160, 4,1)

train_features_speed4 = train_features_speed4.reshape(1196, 4,1)
test_features_speed4 = test_features_speed4.reshape(160, 4,1)

train_features_speed5 = train_features_speed5.reshape(1196, 4,1)
test_features_speed5 = test_features_speed5.reshape(160, 4,1)

train_features_speed6 = train_features_speed6.reshape(1196, 4,1)
test_features_speed6 = test_features_speed6.reshape(160, 4,1)

train_features_speed7 = train_features_speed7.reshape(1196, 4,1)
test_features_speed7 = test_features_speed7.reshape(160, 4,1)

train_features_speed8 = train_features_speed8.reshape(1196, 4,1)
test_features_speed8 = test_features_speed8.reshape(160, 4,1)

train_features_speed9 = train_features_speed9.reshape(1196, 4,1)
test_features_speed9 = test_features_speed9.reshape(160, 4,1)

train_features_speed10 = train_features_speed10.reshape(1196, 4,1)
test_features_speed10 = test_features_speed10.reshape(160, 4,1)

train_features_speed11 = train_features_speed11.reshape(1196, 4,1)
test_features_speed11 = test_features_speed11.reshape(160, 4,1)

train_features_speed12 = train_features_speed12.reshape(1196, 4,1)
test_features_speed12 = test_features_speed12.reshape(160, 4,1)

train_features_speed13 = train_features_speed13.reshape(1196, 4,1)
test_features_speed13 = test_features_speed13.reshape(160, 4,1)

train_features_speed14 = train_features_speed14.reshape(1196, 4,1)
test_features_speed14 = test_features_speed14.reshape(160, 4,1)

train_features_speed15 = train_features_speed15.reshape(1196, 4,1)
test_features_speed15 = test_features_speed15.reshape(160, 4,1)

train_features_speed16 = train_features_speed16.reshape(1196, 4,1)
test_features_speed16 = test_features_speed16.reshape(160, 4,1)

train_features_speed17 = train_features_speed17.reshape(1196, 4,1)
test_features_speed17 = test_features_speed17.reshape(160, 4,1)

train_features_speed18 = train_features_speed18.reshape(1196, 4,1)
test_features_speed18 = test_features_speed18.reshape(160, 4,1)

train_features_speed19 = train_features_speed19.reshape(1196, 4,1)
test_features_speed19 = test_features_speed19.reshape(160, 4,1)

train_features_speed20 = train_features_speed20.reshape(1196, 4,1)
test_features_speed20 = test_features_speed20.reshape(160, 4,1)

In [19]:
def build_model():
    model = tensorflow.keras.models.Sequential()
    model.add(tensorflow.keras.layers.LSTM(18, input_shape=(4,1),return_sequences=True))
    model.add(tensorflow.keras.layers.LSTM(9))
    model.add(tensorflow.keras.layers.Dense(1))

    model.compile(optimizer = 'adam', loss = ['mse'])
    
    return model

In [20]:
from collections import OrderedDict

all_vehicles = OrderedDict()

for i in range(1, 21):
    all_vehicles[f'model_s{i}'] = None

In [21]:
all_vehicles

OrderedDict([('model_s1', None),
             ('model_s2', None),
             ('model_s3', None),
             ('model_s4', None),
             ('model_s5', None),
             ('model_s6', None),
             ('model_s7', None),
             ('model_s8', None),
             ('model_s9', None),
             ('model_s10', None),
             ('model_s11', None),
             ('model_s12', None),
             ('model_s13', None),
             ('model_s14', None),
             ('model_s15', None),
             ('model_s16', None),
             ('model_s17', None),
             ('model_s18', None),
             ('model_s19', None),
             ('model_s20', None)])

In [22]:
for vehicle_name in all_vehicles.keys():
    all_vehicles[vehicle_name] = build_model()

2022-03-17 15:13:11.480406: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
2022-03-17 15:13:11.480497: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (home): /proc/driver/nvidia/version does not exist


In [23]:
all_vehicles

OrderedDict([('model_s1',
              <keras.engine.sequential.Sequential at 0x7fdff6d256a0>),
             ('model_s2',
              <keras.engine.sequential.Sequential at 0x7fdff46124f0>),
             ('model_s3',
              <keras.engine.sequential.Sequential at 0x7fdff447d430>),
             ('model_s4',
              <keras.engine.sequential.Sequential at 0x7fdff435cca0>),
             ('model_s5',
              <keras.engine.sequential.Sequential at 0x7fdff42f4a00>),
             ('model_s6',
              <keras.engine.sequential.Sequential at 0x7fdff4290430>),
             ('model_s7',
              <keras.engine.sequential.Sequential at 0x7fdff42d47f0>),
             ('model_s8',
              <keras.engine.sequential.Sequential at 0x7fdfec7d7d90>),
             ('model_s9',
              <keras.engine.sequential.Sequential at 0x7fdfec766880>),
             ('model_s10',
              <keras.engine.sequential.Sequential at 0x7fdff430a130>),
             ('model_s11',
  

In [24]:
train_features = [
                    train_features_speed1,
                    train_features_speed2,
                    train_features_speed3,
                    train_features_speed4,
                    train_features_speed5,
                    train_features_speed6,
                    train_features_speed7,
                    train_features_speed8,
                    train_features_speed9,
                    train_features_speed10,
                    train_features_speed11,
                    train_features_speed12,
                    train_features_speed13,
                    train_features_speed14,
                    train_features_speed15,
                    train_features_speed16,
                    train_features_speed17,
                    train_features_speed18,
                    train_features_speed19,
                    train_features_speed20
]

In [25]:
train_labels = [
                train_labels_speed1,
                train_labels_speed2,
                train_labels_speed3,
                train_labels_speed4,
                train_labels_speed5,
                train_labels_speed6,
                train_labels_speed7,
                train_labels_speed8,
                train_labels_speed9,
                train_labels_speed10,
                train_labels_speed11,
                train_labels_speed12,
                train_labels_speed13,
                train_labels_speed14,
                train_labels_speed15,
                train_labels_speed16,
                train_labels_speed17,
                train_labels_speed18,
                train_labels_speed19,
                train_labels_speed20,
]

In [26]:
test_features = [
                    test_features_speed1,
                    test_features_speed2,
                    test_features_speed3,
                    test_features_speed4,
                    test_features_speed5,
                    test_features_speed6,
                    test_features_speed7,
                    test_features_speed8,
                    test_features_speed9,
                    test_features_speed10,
                    test_features_speed11,
                    test_features_speed12,
                    test_features_speed13,
                    test_features_speed14,
                    test_features_speed15,
                    test_features_speed16,
                    test_features_speed17,
                    test_features_speed18,
                    test_features_speed19,
                    test_features_speed20,
]

In [27]:
test_labels = [
                test_labels_speed1,
                test_labels_speed2,
                test_labels_speed3,
                test_labels_speed4,
                test_labels_speed5,
                test_labels_speed6,
                test_labels_speed7,
                test_labels_speed8,
                test_labels_speed9,
                test_labels_speed10,
                test_labels_speed11,
                test_labels_speed12,
                test_labels_speed13,
                test_labels_speed14,
                test_labels_speed15,
                test_labels_speed16,
                test_labels_speed17,
                test_labels_speed18,
                test_labels_speed19,
                test_labels_speed20
]

In [28]:
train_features

[array([[[0.24226432],
         [0.26475597],
         [0.27378267],
         [0.27594817]],
 
        [[0.26475597],
         [0.27378267],
         [0.27594817],
         [0.26524959]],
 
        [[0.27378267],
         [0.27594817],
         [0.26524959],
         [0.28114763]],
 
        ...,
 
        [[0.26389525],
         [0.25692183],
         [0.27985955],
         [0.26168265]],
 
        [[0.25692183],
         [0.27985955],
         [0.26168265],
         [0.25818766]],
 
        [[0.27985955],
         [0.26168265],
         [0.25818766],
         [0.26279173]]]),
 array([[[0.22124245],
         [0.18305479],
         [0.19183697],
         [0.17166074]],
 
        [[0.18305479],
         [0.19183697],
         [0.17166074],
         [0.1706459 ]],
 
        [[0.19183697],
         [0.17166074],
         [0.1706459 ],
         [0.17363227]],
 
        ...,
 
        [[0.185271  ],
         [0.17148085],
         [0.17748668],
         [0.1853921 ]],
 
        [[0.17148085

In [29]:
all_veh_hists = []

In [30]:
for i, vehicle_name in enumerate(all_vehicles.keys()):
    model = all_vehicles[vehicle_name]
    history = model.fit(
        train_features[i],
        train_labels[i], 
        batch_size = 64, 
        epochs = 50, 
        shuffle = False, 
        validation_split = .15
    )
    all_veh_hists.append({vehicle_name : history})

Epoch 1/50
16/16 [==============================] - 12s 184ms/step - loss: 0.0396 - val_loss: 0.0195
Epoch 2/50
16/16 [==============================] - 0s 24ms/step - loss: 0.0078 - val_loss: 1.6385e-04
Epoch 3/50
16/16 [==============================] - 0s 16ms/step - loss: 6.6072e-04 - val_loss: 6.1304e-04
Epoch 4/50
16/16 [==============================] - 0s 24ms/step - loss: 1.8693e-04 - val_loss: 1.3765e-04
Epoch 5/50
16/16 [==============================] - 0s 23ms/step - loss: 1.1036e-04 - val_loss: 5.3538e-05
Epoch 6/50
16/16 [==============================] - 0s 16ms/step - loss: 6.3418e-05 - val_loss: 5.4980e-05
Epoch 7/50
16/16 [==============================] - 0s 20ms/step - loss: 5.8026e-05 - val_loss: 5.4413e-05
Epoch 8/50
16/16 [==============================] - 0s 24ms/step - loss: 5.8309e-05 - val_loss: 5.2803e-05
Epoch 9/50
16/16 [==============================] - 0s 24ms/step - loss: 5.7748e-05 - val_loss: 5.2938e-05
Epoch 10/50
16/16 [============================

16/16 [==============================] - 0s 23ms/step - loss: 5.4740e-05 - val_loss: 5.4801e-05
Epoch 28/50
16/16 [==============================] - 0s 21ms/step - loss: 5.4743e-05 - val_loss: 5.4806e-05
Epoch 29/50
16/16 [==============================] - 0s 22ms/step - loss: 5.4746e-05 - val_loss: 5.4812e-05
Epoch 30/50
16/16 [==============================] - 0s 22ms/step - loss: 5.4749e-05 - val_loss: 5.4818e-05
Epoch 31/50
16/16 [==============================] - 0s 23ms/step - loss: 5.4752e-05 - val_loss: 5.4823e-05
Epoch 32/50
16/16 [==============================] - 0s 14ms/step - loss: 5.4755e-05 - val_loss: 5.4829e-05
Epoch 33/50
16/16 [==============================] - 0s 19ms/step - loss: 5.4758e-05 - val_loss: 5.4835e-05
Epoch 34/50
16/16 [==============================] - 0s 22ms/step - loss: 5.4761e-05 - val_loss: 5.4841e-05
Epoch 35/50
16/16 [==============================] - 0s 22ms/step - loss: 5.4764e-05 - val_loss: 5.4848e-05
Epoch 36/50
16/16 [=====================

16/16 [==============================] - 0s 21ms/step - loss: 8.1577e-04 - val_loss: 0.0010
Epoch 4/50
16/16 [==============================] - 0s 21ms/step - loss: 4.5559e-04 - val_loss: 5.5767e-05
Epoch 5/50
16/16 [==============================] - 0s 21ms/step - loss: 1.1046e-04 - val_loss: 6.9383e-05
Epoch 6/50
16/16 [==============================] - 0s 21ms/step - loss: 6.2205e-05 - val_loss: 6.2979e-05
Epoch 7/50
16/16 [==============================] - 0s 21ms/step - loss: 5.8926e-05 - val_loss: 5.1339e-05
Epoch 8/50
16/16 [==============================] - 0s 20ms/step - loss: 5.6643e-05 - val_loss: 5.1722e-05
Epoch 9/50
16/16 [==============================] - 0s 21ms/step - loss: 5.6236e-05 - val_loss: 5.2041e-05
Epoch 10/50
16/16 [==============================] - 0s 21ms/step - loss: 5.6198e-05 - val_loss: 5.1683e-05
Epoch 11/50
16/16 [==============================] - 0s 21ms/step - loss: 5.6177e-05 - val_loss: 5.1867e-05
Epoch 12/50
16/16 [==============================]

16/16 [==============================] - 0s 24ms/step - loss: 5.4752e-05 - val_loss: 6.3987e-05
Epoch 30/50
16/16 [==============================] - 0s 24ms/step - loss: 5.4752e-05 - val_loss: 6.3986e-05
Epoch 31/50
16/16 [==============================] - 0s 22ms/step - loss: 5.4751e-05 - val_loss: 6.3984e-05
Epoch 32/50
16/16 [==============================] - 0s 21ms/step - loss: 5.4751e-05 - val_loss: 6.3983e-05
Epoch 33/50
16/16 [==============================] - 0s 21ms/step - loss: 5.4751e-05 - val_loss: 6.3981e-05
Epoch 34/50
16/16 [==============================] - 0s 21ms/step - loss: 5.4751e-05 - val_loss: 6.3980e-05
Epoch 35/50
16/16 [==============================] - 0s 21ms/step - loss: 5.4750e-05 - val_loss: 6.3978e-05
Epoch 36/50
16/16 [==============================] - 0s 21ms/step - loss: 5.4750e-05 - val_loss: 6.3977e-05
Epoch 37/50
16/16 [==============================] - 0s 21ms/step - loss: 5.4750e-05 - val_loss: 6.3975e-05
Epoch 38/50
16/16 [=====================

16/16 [==============================] - 0s 24ms/step - loss: 9.1216e-05 - val_loss: 5.9819e-05
Epoch 6/50
16/16 [==============================] - 0s 25ms/step - loss: 5.7830e-05 - val_loss: 6.0252e-05
Epoch 7/50
16/16 [==============================] - 0s 26ms/step - loss: 5.5458e-05 - val_loss: 5.8404e-05
Epoch 8/50
16/16 [==============================] - 0s 25ms/step - loss: 5.4845e-05 - val_loss: 5.7579e-05
Epoch 9/50
16/16 [==============================] - 0s 23ms/step - loss: 5.4727e-05 - val_loss: 5.7597e-05
Epoch 10/50
16/16 [==============================] - 0s 23ms/step - loss: 5.4651e-05 - val_loss: 5.7623e-05
Epoch 11/50
16/16 [==============================] - 0s 23ms/step - loss: 5.4665e-05 - val_loss: 5.7599e-05
Epoch 12/50
16/16 [==============================] - 0s 23ms/step - loss: 5.4663e-05 - val_loss: 5.7613e-05
Epoch 13/50
16/16 [==============================] - 0s 23ms/step - loss: 5.4666e-05 - val_loss: 5.7608e-05
Epoch 14/50
16/16 [=========================

16/16 [==============================] - 0s 22ms/step - loss: 5.8940e-05 - val_loss: 5.1039e-05
Epoch 32/50
16/16 [==============================] - 0s 22ms/step - loss: 5.8953e-05 - val_loss: 5.1038e-05
Epoch 33/50
16/16 [==============================] - 0s 22ms/step - loss: 5.8967e-05 - val_loss: 5.1036e-05
Epoch 34/50
16/16 [==============================] - 0s 22ms/step - loss: 5.8981e-05 - val_loss: 5.1035e-05
Epoch 35/50
16/16 [==============================] - 0s 17ms/step - loss: 5.8996e-05 - val_loss: 5.1035e-05
Epoch 36/50
16/16 [==============================] - 0s 22ms/step - loss: 5.9011e-05 - val_loss: 5.1035e-05
Epoch 37/50
16/16 [==============================] - 0s 22ms/step - loss: 5.9026e-05 - val_loss: 5.1036e-05
Epoch 38/50
16/16 [==============================] - 0s 22ms/step - loss: 5.9042e-05 - val_loss: 5.1037e-05
Epoch 39/50
16/16 [==============================] - 0s 21ms/step - loss: 5.9058e-05 - val_loss: 5.1039e-05
Epoch 40/50
16/16 [=====================

16/16 [==============================] - 0s 21ms/step - loss: 5.8150e-05 - val_loss: 5.9379e-05
Epoch 8/50
16/16 [==============================] - 0s 21ms/step - loss: 5.8104e-05 - val_loss: 5.9444e-05
Epoch 9/50
16/16 [==============================] - 0s 21ms/step - loss: 5.8108e-05 - val_loss: 5.9408e-05
Epoch 10/50
16/16 [==============================] - 0s 21ms/step - loss: 5.8108e-05 - val_loss: 5.9425e-05
Epoch 11/50
16/16 [==============================] - 0s 21ms/step - loss: 5.8111e-05 - val_loss: 5.9420e-05
Epoch 12/50
16/16 [==============================] - 0s 22ms/step - loss: 5.8113e-05 - val_loss: 5.9423e-05
Epoch 13/50
16/16 [==============================] - 0s 21ms/step - loss: 5.8117e-05 - val_loss: 5.9424e-05
Epoch 14/50
16/16 [==============================] - 0s 20ms/step - loss: 5.8119e-05 - val_loss: 5.9425e-05
Epoch 15/50
16/16 [==============================] - 0s 22ms/step - loss: 5.8122e-05 - val_loss: 5.9426e-05
Epoch 16/50
16/16 [=======================

16/16 [==============================] - 0s 23ms/step - loss: 5.9252e-05 - val_loss: 4.8749e-05
Epoch 34/50
16/16 [==============================] - 0s 23ms/step - loss: 5.9255e-05 - val_loss: 4.8749e-05
Epoch 35/50
16/16 [==============================] - 0s 23ms/step - loss: 5.9258e-05 - val_loss: 4.8748e-05
Epoch 36/50
16/16 [==============================] - 0s 24ms/step - loss: 5.9261e-05 - val_loss: 4.8748e-05
Epoch 37/50
16/16 [==============================] - 0s 28ms/step - loss: 5.9264e-05 - val_loss: 4.8748e-05
Epoch 38/50
16/16 [==============================] - 0s 26ms/step - loss: 5.9267e-05 - val_loss: 4.8748e-05
Epoch 39/50
16/16 [==============================] - 0s 27ms/step - loss: 5.9270e-05 - val_loss: 4.8748e-05
Epoch 40/50
16/16 [==============================] - 0s 24ms/step - loss: 5.9273e-05 - val_loss: 4.8748e-05
Epoch 41/50
16/16 [==============================] - 0s 24ms/step - loss: 5.9277e-05 - val_loss: 4.8748e-05
Epoch 42/50
16/16 [=====================

16/16 [==============================] - 0s 22ms/step - loss: 5.2313e-05 - val_loss: 6.0496e-05
Epoch 10/50
16/16 [==============================] - 0s 21ms/step - loss: 5.2340e-05 - val_loss: 6.0375e-05
Epoch 11/50
16/16 [==============================] - 0s 22ms/step - loss: 5.2316e-05 - val_loss: 6.0396e-05
Epoch 12/50
16/16 [==============================] - 0s 21ms/step - loss: 5.2316e-05 - val_loss: 6.0392e-05
Epoch 13/50
16/16 [==============================] - 0s 21ms/step - loss: 5.2318e-05 - val_loss: 6.0390e-05
Epoch 14/50
16/16 [==============================] - 0s 22ms/step - loss: 5.2318e-05 - val_loss: 6.0392e-05
Epoch 15/50
16/16 [==============================] - 0s 21ms/step - loss: 5.2319e-05 - val_loss: 6.0391e-05
Epoch 16/50
16/16 [==============================] - 0s 21ms/step - loss: 5.2320e-05 - val_loss: 6.0391e-05
Epoch 17/50
16/16 [==============================] - 0s 22ms/step - loss: 5.2320e-05 - val_loss: 6.0391e-05
Epoch 18/50
16/16 [=====================

16/16 [==============================] - 0s 22ms/step - loss: 5.4576e-05 - val_loss: 5.5827e-05
Epoch 36/50
16/16 [==============================] - 0s 21ms/step - loss: 5.4581e-05 - val_loss: 5.5824e-05
Epoch 37/50
16/16 [==============================] - 0s 21ms/step - loss: 5.4586e-05 - val_loss: 5.5822e-05
Epoch 38/50
16/16 [==============================] - 0s 20ms/step - loss: 5.4592e-05 - val_loss: 5.5819e-05
Epoch 39/50
16/16 [==============================] - 0s 22ms/step - loss: 5.4597e-05 - val_loss: 5.5816e-05
Epoch 40/50
16/16 [==============================] - 0s 22ms/step - loss: 5.4602e-05 - val_loss: 5.5814e-05
Epoch 41/50
16/16 [==============================] - 0s 21ms/step - loss: 5.4608e-05 - val_loss: 5.5811e-05
Epoch 42/50
16/16 [==============================] - 0s 21ms/step - loss: 5.4614e-05 - val_loss: 5.5808e-05
Epoch 43/50
16/16 [==============================] - 0s 27ms/step - loss: 5.4619e-05 - val_loss: 5.5805e-05
Epoch 44/50
16/16 [=====================

16/16 [==============================] - 0s 25ms/step - loss: 5.4290e-05 - val_loss: 5.5015e-05
Epoch 12/50
16/16 [==============================] - 0s 22ms/step - loss: 5.4290e-05 - val_loss: 5.5016e-05
Epoch 13/50
16/16 [==============================] - 0s 21ms/step - loss: 5.4295e-05 - val_loss: 5.5016e-05
Epoch 14/50
16/16 [==============================] - 0s 21ms/step - loss: 5.4299e-05 - val_loss: 5.5016e-05
Epoch 15/50
16/16 [==============================] - 0s 22ms/step - loss: 5.4304e-05 - val_loss: 5.5017e-05
Epoch 16/50
16/16 [==============================] - 0s 22ms/step - loss: 5.4308e-05 - val_loss: 5.5017e-05
Epoch 17/50
16/16 [==============================] - 0s 21ms/step - loss: 5.4313e-05 - val_loss: 5.5017e-05
Epoch 18/50
16/16 [==============================] - 0s 22ms/step - loss: 5.4317e-05 - val_loss: 5.5018e-05
Epoch 19/50
16/16 [==============================] - 0s 22ms/step - loss: 5.4322e-05 - val_loss: 5.5018e-05
Epoch 20/50
16/16 [=====================

16/16 [==============================] - 0s 21ms/step - loss: 5.4222e-05 - val_loss: 5.7901e-05
Epoch 38/50
16/16 [==============================] - 0s 22ms/step - loss: 5.4222e-05 - val_loss: 5.7898e-05
Epoch 39/50
16/16 [==============================] - 0s 21ms/step - loss: 5.4222e-05 - val_loss: 5.7896e-05
Epoch 40/50
16/16 [==============================] - 0s 22ms/step - loss: 5.4222e-05 - val_loss: 5.7893e-05
Epoch 41/50
16/16 [==============================] - 0s 21ms/step - loss: 5.4222e-05 - val_loss: 5.7890e-05
Epoch 42/50
16/16 [==============================] - 0s 21ms/step - loss: 5.4221e-05 - val_loss: 5.7887e-05
Epoch 43/50
16/16 [==============================] - 0s 22ms/step - loss: 5.4221e-05 - val_loss: 5.7884e-05
Epoch 44/50
16/16 [==============================] - 0s 22ms/step - loss: 5.4221e-05 - val_loss: 5.7881e-05
Epoch 45/50
16/16 [==============================] - 0s 21ms/step - loss: 5.4221e-05 - val_loss: 5.7878e-05
Epoch 46/50
16/16 [=====================

16/16 [==============================] - 0s 21ms/step - loss: 5.8216e-05 - val_loss: 5.7525e-05
Epoch 14/50
16/16 [==============================] - 0s 21ms/step - loss: 5.8218e-05 - val_loss: 5.7527e-05
Epoch 15/50
16/16 [==============================] - 0s 21ms/step - loss: 5.8218e-05 - val_loss: 5.7526e-05
Epoch 16/50
16/16 [==============================] - 0s 21ms/step - loss: 5.8220e-05 - val_loss: 5.7526e-05
Epoch 17/50
16/16 [==============================] - 0s 21ms/step - loss: 5.8221e-05 - val_loss: 5.7526e-05
Epoch 18/50
16/16 [==============================] - 0s 21ms/step - loss: 5.8222e-05 - val_loss: 5.7526e-05
Epoch 19/50
16/16 [==============================] - 0s 21ms/step - loss: 5.8223e-05 - val_loss: 5.7525e-05
Epoch 20/50
16/16 [==============================] - 0s 21ms/step - loss: 5.8224e-05 - val_loss: 5.7525e-05
Epoch 21/50
16/16 [==============================] - 0s 21ms/step - loss: 5.8225e-05 - val_loss: 5.7525e-05
Epoch 22/50
16/16 [=====================

16/16 [==============================] - 0s 21ms/step - loss: 5.3589e-05 - val_loss: 6.0837e-05
Epoch 40/50
16/16 [==============================] - 0s 21ms/step - loss: 5.3596e-05 - val_loss: 6.0840e-05
Epoch 41/50
16/16 [==============================] - 0s 21ms/step - loss: 5.3604e-05 - val_loss: 6.0843e-05
Epoch 42/50
16/16 [==============================] - 0s 22ms/step - loss: 5.3612e-05 - val_loss: 6.0846e-05
Epoch 43/50
16/16 [==============================] - 0s 20ms/step - loss: 5.3621e-05 - val_loss: 6.0849e-05
Epoch 44/50
16/16 [==============================] - 0s 21ms/step - loss: 5.3629e-05 - val_loss: 6.0852e-05
Epoch 45/50
16/16 [==============================] - 0s 21ms/step - loss: 5.3638e-05 - val_loss: 6.0855e-05
Epoch 46/50
16/16 [==============================] - 0s 21ms/step - loss: 5.3646e-05 - val_loss: 6.0858e-05
Epoch 47/50
16/16 [==============================] - 0s 20ms/step - loss: 5.3655e-05 - val_loss: 6.0861e-05
Epoch 48/50
16/16 [=====================

In [54]:
# predictions
all_predictions = []

for i, vehicle_name in enumerate(all_vehicles.keys()):
    model = all_vehicles[vehicle_name]
    preds = model.predict(test_features[i])
    all_predictions.append({vehicle_name : preds})

In [32]:
all_predictions


[{'model_s1': array([[0.26827702],
         [0.26783276],
         [0.2674869 ],
         [0.2677141 ],
         [0.2683103 ],
         [0.27009374],
         [0.26909074],
         [0.26742992],
         [0.2677823 ],
         [0.2683784 ],
         [0.268519  ],
         [0.26897964],
         [0.26702565],
         [0.26920086],
         [0.26953873],
         [0.27083334],
         [0.2723667 ],
         [0.2714991 ],
         [0.27091956],
         [0.26964954],
         [0.26910144],
         [0.26785636],
         [0.268717  ],
         [0.26925284],
         [0.26816764],
         [0.26714298],
         [0.26782012],
         [0.26906815],
         [0.26858082],
         [0.26740453],
         [0.26802713],
         [0.26818037],
         [0.2688046 ],
         [0.26779088],
         [0.26782894],
         [0.26920766],
         [0.26874626],
         [0.26971024],
         [0.27000687],
         [0.27013102],
         [0.26894575],
         [0.26958525],
         [0.2686326 ],

In [33]:
test_features

[array([[[0.26632546],
         [0.2686336 ],
         [0.26811149],
         [0.26517961]],
 
        [[0.2686336 ],
         [0.26811149],
         [0.26517961],
         [0.25399104]],
 
        [[0.26811149],
         [0.26517961],
         [0.25399104],
         [0.2752721 ]],
 
        [[0.26517961],
         [0.25399104],
         [0.2752721 ],
         [0.27834271]],
 
        [[0.25399104],
         [0.2752721 ],
         [0.27834271],
         [0.26695911]],
 
        [[0.2752721 ],
         [0.27834271],
         [0.26695911],
         [0.26125258]],
 
        [[0.27834271],
         [0.26695911],
         [0.26125258],
         [0.26657515]],
 
        [[0.26695911],
         [0.26125258],
         [0.26657515],
         [0.26375124]],
 
        [[0.26125258],
         [0.26657515],
         [0.26375124],
         [0.2813927 ]],
 
        [[0.26657515],
         [0.26375124],
         [0.2813927 ],
         [0.25453447]],
 
        [[0.26375124],
         [0.2813927 ],
    

In [34]:
test_labels

[array([0.25399104, 0.2752721 , 0.27834271, 0.26695911, 0.26125258,
        0.26657515, 0.26375124, 0.2813927 , 0.25453447, 0.27190895,
        0.26628769, 0.26434431, 0.28452071, 0.27701627, 0.27798092,
        0.27312487, 0.28054622, 0.26162525, 0.26096348, 0.27432174,
        0.27661314, 0.26188596, 0.2569725 , 0.26959021, 0.27700402,
        0.26272661, 0.26396655, 0.26352743, 0.27459396, 0.26685063,
        0.25837119, 0.27631887, 0.26218461, 0.26937564, 0.27249355,
        0.27921676, 0.26127546, 0.27580824, 0.27716318, 0.26186056,
        0.25947179, 0.27494049, 0.2735853 , 0.26150012, 0.25822203,
        0.26493939, 0.27139488, 0.27289082, 0.26879976, 0.26179916,
        0.2553693 , 0.25592932, 0.26492653, 0.27808977, 0.27332279,
        0.26275665, 0.27341048, 0.27250304, 0.26906061, 0.27350074,
        0.27451602, 0.27239434, 0.28090579, 0.26606726, 0.26448141,
        0.25970287, 0.26928427, 0.26463222, 0.27248964, 0.2763984 ,
        0.26829844, 0.25940201, 0.27007073, 0.25

In [35]:
len(test_features_speed1)

160

In [36]:
all_veh_windows = []

for feature in test_features:
    x = feature[-1:]
    all_veh_windows.append(x)

In [37]:
np.array(all_veh_windows).shape

(20, 1, 4, 1)

In [38]:
# all_veh_windows
for car in all_veh_windows:
    print(car.shape)
    print(type(car))

(1, 4, 1)
<class 'numpy.ndarray'>
(1, 4, 1)
<class 'numpy.ndarray'>
(1, 4, 1)
<class 'numpy.ndarray'>
(1, 4, 1)
<class 'numpy.ndarray'>
(1, 4, 1)
<class 'numpy.ndarray'>
(1, 4, 1)
<class 'numpy.ndarray'>
(1, 4, 1)
<class 'numpy.ndarray'>
(1, 4, 1)
<class 'numpy.ndarray'>
(1, 4, 1)
<class 'numpy.ndarray'>
(1, 4, 1)
<class 'numpy.ndarray'>
(1, 4, 1)
<class 'numpy.ndarray'>
(1, 4, 1)
<class 'numpy.ndarray'>
(1, 4, 1)
<class 'numpy.ndarray'>
(1, 4, 1)
<class 'numpy.ndarray'>
(1, 4, 1)
<class 'numpy.ndarray'>
(1, 4, 1)
<class 'numpy.ndarray'>
(1, 4, 1)
<class 'numpy.ndarray'>
(1, 4, 1)
<class 'numpy.ndarray'>
(1, 4, 1)
<class 'numpy.ndarray'>
(1, 4, 1)
<class 'numpy.ndarray'>


In [39]:
names = list(all_vehicles.keys())

In [40]:
names

['model_s1',
 'model_s2',
 'model_s3',
 'model_s4',
 'model_s5',
 'model_s6',
 'model_s7',
 'model_s8',
 'model_s9',
 'model_s10',
 'model_s11',
 'model_s12',
 'model_s13',
 'model_s14',
 'model_s15',
 'model_s16',
 'model_s17',
 'model_s18',
 'model_s19',
 'model_s20']

In [41]:
all_speed_windows = {car: [] for car in names}

In [42]:
all_speed_windows

{'model_s1': [],
 'model_s2': [],
 'model_s3': [],
 'model_s4': [],
 'model_s5': [],
 'model_s6': [],
 'model_s7': [],
 'model_s8': [],
 'model_s9': [],
 'model_s10': [],
 'model_s11': [],
 'model_s12': [],
 'model_s13': [],
 'model_s14': [],
 'model_s15': [],
 'model_s16': [],
 'model_s17': [],
 'model_s18': [],
 'model_s19': [],
 'model_s20': []}

In [43]:
all

<function all(iterable, /)>

In [44]:
reyan_ka_keera = np.array(all_veh_windows).tolist()

In [45]:
len(reyan_ka_keera)

20

In [46]:
reyan_ka_keera[0]

[[[0.27479596365664594],
  [0.27486037631511645],
  [0.26318528426741605],
  [0.27129494398750853]]]

In [47]:
type(reyan_ka_keera[0])

list

In [48]:
reyan_ka_keera[0][0]

[[0.27479596365664594],
 [0.27486037631511645],
 [0.26318528426741605],
 [0.27129494398750853]]

In [49]:
temp = np.array([])
for val in np.array(all_veh_windows):
    np.append(temp, val.reshape(1,4))

print(temp)
print(type(temp))
print(np.array(temp).shape)

# temp.tolist()

[]
<class 'numpy.ndarray'>
(0,)


In [50]:
for i, individual_window in enumerate(all_veh_windows):
    # print(type(individual_window[0]))
    # speed
    for value in individual_window:
        all_speed_windows[names[i]].append(list(value))
        print(type(list(value)))

<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>


In [51]:
all_speed_windows['model_s1']

[[array([0.27479596]),
  array([0.27486038]),
  array([0.26318528]),
  array([0.27129494])]]

In [52]:
all_speed_windows

{'model_s1': [[array([0.27479596]),
   array([0.27486038]),
   array([0.26318528]),
   array([0.27129494])]],
 'model_s2': [[array([0.19078576]),
   array([0.16780094]),
   array([0.18919584]),
   array([0.18059634])]],
 'model_s3': [[array([0.2949423]),
   array([0.30959883]),
   array([0.29716413]),
   array([0.29932542])]],
 'model_s4': [[array([0.27983255]),
   array([0.26714072]),
   array([0.2780636]),
   array([0.25888145])]],
 'model_s5': [[array([0.22140818]),
   array([0.22610466]),
   array([0.2221694]),
   array([0.23305337])]],
 'model_s6': [[array([0.13900969]),
   array([0.12331134]),
   array([0.11842333]),
   array([0.13454627])]],
 'model_s7': [[array([0.23430184]),
   array([0.21960389]),
   array([0.2284022]),
   array([0.23305337])]],
 'model_s8': [[array([0.08924825]),
   array([0.09893348]),
   array([0.10153443]),
   array([0.08829599])]],
 'model_s9': [[array([0.05862583]),
   array([0.07963434]),
   array([0.06293124]),
   array([0.0702764])]],
 'model_s10': [

In [53]:
#position
out_append_pos=[]
for i in range(40):
    temp=np.array(s_list).reshape(1,4,17)
    pred=model_p.predict(temp)
    # print(pred[0])
    out_append_pos.append(list(pred[0]))
    p_list.append(list(pred[0]))
    p_list.pop(0)

NameError: name 's_list' is not defined

In [55]:
len(all_predictions[0]['model_s1'])

160

In [ ]:
for i in range(15):
    

In [56]:
len(test_features_speed1)

160

In [57]:
len(test_labels_speed1)

160

In [58]:
np.array(test_features_speed1).shape  # 164 layers 4 rows 1 column

(160, 4, 1)

In [59]:
np.array(test_features_speed1)

array([[[0.26632546],
        [0.2686336 ],
        [0.26811149],
        [0.26517961]],

       [[0.2686336 ],
        [0.26811149],
        [0.26517961],
        [0.25399104]],

       [[0.26811149],
        [0.26517961],
        [0.25399104],
        [0.2752721 ]],

       [[0.26517961],
        [0.25399104],
        [0.2752721 ],
        [0.27834271]],

       [[0.25399104],
        [0.2752721 ],
        [0.27834271],
        [0.26695911]],

       [[0.2752721 ],
        [0.27834271],
        [0.26695911],
        [0.26125258]],

       [[0.27834271],
        [0.26695911],
        [0.26125258],
        [0.26657515]],

       [[0.26695911],
        [0.26125258],
        [0.26657515],
        [0.26375124]],

       [[0.26125258],
        [0.26657515],
        [0.26375124],
        [0.2813927 ]],

       [[0.26657515],
        [0.26375124],
        [0.2813927 ],
        [0.25453447]],

       [[0.26375124],
        [0.2813927 ],
        [0.25453447],
        [0.27190895]],

       [[0

In [60]:
np.array(test_labels_speed1).shape

(160,)

In [61]:
test_features_speed1 = np.array(test_features_speed1)

In [62]:
x.shape

(1, 4, 1)

In [63]:
y = test_features_speed1[-1]
# y.shape
y=y.reshape(1,4,1)

In [64]:
# predictions
# all_predictions = []
pred_speed1 = []
z = all_vehicles['model_s1'].predict(y)

#     model = all_vehicles[vehicle_name]
#     preds = model.predict(test_features[i])
#     all_predictions.append({vehicle_name : preds})

In [65]:
y[0][1:]

array([[0.27486038],
       [0.26318528],
       [0.27129494]])

In [66]:
np.append(y[0][1:], z)

array([0.27486038, 0.26318528, 0.27129494, 0.26980233])

In [67]:
for i in range(15):
    # parse
    last_val = train_features_speed1[-1]
    last_val = last_val.reshape(1, 4, 1)
        
    # predict
    print(f'Iteration #{i+1}')
    predicted_val = all_vehicles['model_s1'].predict(last_val)
    
    # 
    print(f'Before: ', sep='')
    print(last_val)
    print()
    last_val = np.append(last_val[0][1:], predicted_val)
    print(f'After: ', sep='')
    print(last_val)
    print()
    
    print(f'#'* 20)
    print()
    

Iteration #1
Before: 
[[[0.27985955]
  [0.26168265]
  [0.25818766]
  [0.26279173]]]

After: 
[0.26168265 0.25818766 0.26279173 0.26835501]

####################

Iteration #2
Before: 
[[[0.27985955]
  [0.26168265]
  [0.25818766]
  [0.26279173]]]

After: 
[0.26168265 0.25818766 0.26279173 0.26835501]

####################

Iteration #3
Before: 
[[[0.27985955]
  [0.26168265]
  [0.25818766]
  [0.26279173]]]

After: 
[0.26168265 0.25818766 0.26279173 0.26835501]

####################

Iteration #4
Before: 
[[[0.27985955]
  [0.26168265]
  [0.25818766]
  [0.26279173]]]

After: 
[0.26168265 0.25818766 0.26279173 0.26835501]

####################

Iteration #5
Before: 
[[[0.27985955]
  [0.26168265]
  [0.25818766]
  [0.26279173]]]

After: 
[0.26168265 0.25818766 0.26279173 0.26835501]

####################

Iteration #6
Before: 
[[[0.27985955]
  [0.26168265]
  [0.25818766]
  [0.26279173]]]

After: 
[0.26168265 0.25818766 0.26279173 0.26835501]

####################

Iteration #7
Before: 
[[[0.2

In [68]:
# now the yeinn starts
resultant_dataframe_to_be = {}


for i in range(20):
    for j in range(20):
        # parse
        # DYANMIC SHIT
        last_val = train_features[j][-1]

        last_val = last_val.reshape(1, 4, 1) 

        # predict
        # DYNAMIC SHIT ...DONE....
        predicted_val = all_vehicles[f'model_s{i+1}'].predict(last_val)

        # FOR THE DATAFRAME THAT HAS TO BE GIVEN TO THE CLUSTERING ALLGORITHM
        if names[i] in resultant_dataframe_to_be:
            resultant_dataframe_to_be[names[i]].append(predicted_val)
        else:
            resultant_dataframe_to_be[names[i]] = [predicted_val]

        # 
        last_val = np.append(last_val[0][1:], predicted_val)
   

In [69]:
names

['model_s1',
 'model_s2',
 'model_s3',
 'model_s4',
 'model_s5',
 'model_s6',
 'model_s7',
 'model_s8',
 'model_s9',
 'model_s10',
 'model_s11',
 'model_s12',
 'model_s13',
 'model_s14',
 'model_s15',
 'model_s16',
 'model_s17',
 'model_s18',
 'model_s19',
 'model_s20']

In [70]:
len(names)

20

In [71]:
test_features_speed1

array([[[0.26632546],
        [0.2686336 ],
        [0.26811149],
        [0.26517961]],

       [[0.2686336 ],
        [0.26811149],
        [0.26517961],
        [0.25399104]],

       [[0.26811149],
        [0.26517961],
        [0.25399104],
        [0.2752721 ]],

       [[0.26517961],
        [0.25399104],
        [0.2752721 ],
        [0.27834271]],

       [[0.25399104],
        [0.2752721 ],
        [0.27834271],
        [0.26695911]],

       [[0.2752721 ],
        [0.27834271],
        [0.26695911],
        [0.26125258]],

       [[0.27834271],
        [0.26695911],
        [0.26125258],
        [0.26657515]],

       [[0.26695911],
        [0.26125258],
        [0.26657515],
        [0.26375124]],

       [[0.26125258],
        [0.26657515],
        [0.26375124],
        [0.2813927 ]],

       [[0.26657515],
        [0.26375124],
        [0.2813927 ],
        [0.25453447]],

       [[0.26375124],
        [0.2813927 ],
        [0.25453447],
        [0.27190895]],

       [[0

In [72]:
test_features[0] == test_features_speed1

array([[[ True],
        [ True],
        [ True],
        [ True]],

       [[ True],
        [ True],
        [ True],
        [ True]],

       [[ True],
        [ True],
        [ True],
        [ True]],

       [[ True],
        [ True],
        [ True],
        [ True]],

       [[ True],
        [ True],
        [ True],
        [ True]],

       [[ True],
        [ True],
        [ True],
        [ True]],

       [[ True],
        [ True],
        [ True],
        [ True]],

       [[ True],
        [ True],
        [ True],
        [ True]],

       [[ True],
        [ True],
        [ True],
        [ True]],

       [[ True],
        [ True],
        [ True],
        [ True]],

       [[ True],
        [ True],
        [ True],
        [ True]],

       [[ True],
        [ True],
        [ True],
        [ True]],

       [[ True],
        [ True],
        [ True],
        [ True]],

       [[ True],
        [ True],
        [ True],
        [ True]],

       [[ True],
   

In [76]:
resultant_dataframe_to_be

{'model_s1': [array([[0.268355]], dtype=float32),
  array([[0.23901588]], dtype=float32),
  array([[0.27886778]], dtype=float32),
  array([[0.26663208]], dtype=float32),
  array([[0.2546829]], dtype=float32),
  array([[0.2199735]], dtype=float32),
  array([[0.25573748]], dtype=float32),
  array([[0.211696]], dtype=float32),
  array([[0.19914718]], dtype=float32),
  array([[0.2006685]], dtype=float32),
  array([[0.2636505]], dtype=float32),
  array([[0.27833056]], dtype=float32),
  array([[0.2555723]], dtype=float32),
  array([[0.2630593]], dtype=float32),
  array([[0.24215485]], dtype=float32),
  array([[0.26781482]], dtype=float32),
  array([[0.25855663]], dtype=float32),
  array([[0.26349118]], dtype=float32),
  array([[0.2304233]], dtype=float32),
  array([[0.27176097]], dtype=float32)],
 'model_s2': [array([[0.189734]], dtype=float32),
  array([[0.17841126]], dtype=float32),
  array([[0.19376762]], dtype=float32),
  array([[0.18896589]], dtype=float32),
  array([[0.18439619]], dtyp

In [80]:
resultant_dataframe_to_be = {'model_s1': [0.268355,
  0.23901588,
  0.27886778,
  0.26663208,
  0.2546829,
  0.2199735,
  0.25573748,
  0.211696,
  0.19914718,
  0.2006685,
  0.2636505,
  0.27833056,
  0.2555723,
  0.2630593,
  0.24215485,
  0.26781482,
  0.25855663,
  0.26349118,
  0.2304233,
  0.27176097],
 'model_s2': [0.189734,
  0.17841126,
  0.19376762,
  0.18896589,
  0.18439619,
  0.17131118,
  0.18482815,
  0.16819146,
  0.16356021,
  0.16408154,
  0.18785405,
  0.19352888,
  0.18472265,
  0.18767072,
  0.17957117,
  0.18944125,
  0.18588912,
  0.1877663,
  0.17515007,
  0.19099753],
 'model_s3': [0.28429598,
  0.251899,
  0.29626888,
  0.28255928,
  0.2691638,
  0.23111038,
  0.27028704,
  0.22229402,
  0.20897555,
  0.2106313,
  0.27915013,
  0.29572046,
  0.27017054,
  0.27838945,
  0.25539345,
  0.2838595,
  0.27346295,
  0.27902,
  0.24253656,
  0.28824335],
 'model_s4': [0.26842326,
  0.2433466,
  0.27785116,
  0.2672209,
  0.25674218,
  0.22707768,
  0.25757244,
  0.22025424,
  0.20987797,
  0.21121122,
  0.26451305,
  0.27743945,
  0.25757977,
  0.2638276,
  0.24612981,
  0.26823148,
  0.260067,
  0.26443827,
  0.2360953,
  0.2715972],
 'model_s5': [0.23999153,
  0.21472977,
  0.24926198,
  0.23873457,
  0.2282897,
  0.19812724,
  0.22914405,
  0.19106579,
  0.18026458,
  0.18164156,
  0.23605841,
  0.2488687,
  0.22908531,
  0.23542923,
  0.21751225,
  0.23972607,
  0.2316397,
  0.2359805,
  0.20731564,
  0.24309097],
 'model_s6': [0.14591026,
  0.13683248,
  0.14932306,
  0.14547838,
  0.14168562,
  0.13092116,
  0.14198571,
  0.1284337,
  0.12464276,
  0.12512934,
  0.14449866,
  0.149173,
  0.1419907,
  0.14424708,
  0.13784304,
  0.14584547,
  0.14288817,
  0.1444712,
  0.13419983,
  0.14706081],
 'model_s7': [0.23784406,
  0.2169937,
  0.24548428,
  0.23672982,
  0.22813992,
  0.20342891,
  0.228862,
  0.19761962,
  0.18879205,
  0.18988898,
  0.23455359,
  0.24512315,
  0.2287986,
  0.23405546,
  0.21926443,
  0.23757271,
  0.23089759,
  0.23446415,
  0.21090642,
  0.24036932],
 'model_s8': [0.11010665,
  0.10283425,
  0.11277869,
  0.10973837,
  0.10673397,
  0.09806231,
  0.10698166,
  0.09602574,
  0.0929159,
  0.09330812,
  0.10897224,
  0.11265955,
  0.10696449,
  0.10878921,
  0.1036339,
  0.11002877,
  0.1076969,
  0.10894622,
  0.1006997,
  0.11099794],
 'model_s9': [0.10083146,
  0.08718686,
  0.10598966,
  0.10027996,
  0.09453975,
  0.07805077,
  0.09496625,
  0.07423256,
  0.06833701,
  0.06912487,
  0.09877774,
  0.10577935,
  0.09502739,
  0.09833908,
  0.08876453,
  0.1008283,
  0.09634358,
  0.09875442,
  0.08317322,
  0.10261623],
 'model_s10': [0.07619749,
  0.07311228,
  0.07720964,
  0.07596017,
  0.07475802,
  0.07110591,
  0.07488304,
  0.0701813,
  0.06878635,
  0.06893991,
  0.07567877,
  0.07714283,
  0.07483815,
  0.07565459,
  0.07342349,
  0.0760844,
  0.07516194,
  0.0756492,
  0.07219125,
  0.07650103],
 'model_s11': [0.2540986,
  0.23224005,
  0.26184744,
  0.2526312,
  0.24381045,
  0.21846409,
  0.24463893,
  0.21241589,
  0.20340401,
  0.20443448,
  0.25047472,
  0.26139474,
  0.24444664,
  0.25013247,
  0.23449226,
  0.2535344,
  0.24669318,
  0.25031266,
  0.22593327,
  0.25652993],
 'model_s12': [0.29045808,
  0.27125102,
  0.29733554,
  0.2892123,
  0.28142902,
  0.25909415,
  0.2821469,
  0.25378913,
  0.245861,
  0.24678206,
  0.28730163,
  0.29694724,
  0.28199172,
  0.28696173,
  0.2732461,
  0.2900098,
  0.28396365,
  0.28716794,
  0.26570165,
  0.29263666],
 'model_s13': [0.23859434,
  0.21760204,
  0.24614345,
  0.23734379,
  0.22878373,
  0.20408371,
  0.22954026,
  0.19822153,
  0.18937764,
  0.19044203,
  0.23520859,
  0.2457489,
  0.2294277,
  0.23478964,
  0.21984127,
  0.23819718,
  0.23155484,
  0.23508945,
  0.21149404,
  0.24103439],
 'model_s14': [0.25322416,
  0.23398343,
  0.26013935,
  0.2520868,
  0.24424599,
  0.22156228,
  0.2449404,
  0.21616311,
  0.2079991,
  0.2089792,
  0.25013083,
  0.2597858,
  0.24482521,
  0.2497457,
  0.23603049,
  0.252865,
  0.24678792,
  0.2500249,
  0.22836314,
  0.2554613],
 'model_s15': [0.21310496,
  0.19373834,
  0.2203354,
  0.21212734,
  0.20407408,
  0.18122318,
  0.20472965,
  0.1759395,
  0.16792423,
  0.1689369,
  0.21006276,
  0.22001152,
  0.20470004,
  0.20956226,
  0.19586095,
  0.2129093,
  0.20664212,
  0.2099946,
  0.18813303,
  0.21551669],
 'model_s16': [0.26889086,
  0.24185754,
  0.2788366,
  0.26743978,
  0.256284,
  0.22436816,
  0.2572202,
  0.21689892,
  0.20556934,
  0.20697802,
  0.26460794,
  0.27836436,
  0.2571411,
  0.26396737,
  0.24479412,
  0.26853308,
  0.2598617,
  0.26449198,
  0.23400298,
  0.2721732],
 'model_s17': [0.24198887,
  0.21769403,
  0.25076887,
  0.24048135,
  0.23057683,
  0.20229764,
  0.2314672,
  0.19562276,
  0.1856259,
  0.18680473,
  0.2380217,
  0.2502932,
  0.2313092,
  0.2375621,
  0.22024322,
  0.24148142,
  0.23378667,
  0.23787025,
  0.21069036,
  0.24479906],
 'model_s18': [0.25883192,
  0.23623371,
  0.2670013,
  0.25744122,
  0.24822442,
  0.22182459,
  0.2490474,
  0.21556571,
  0.20620224,
  0.20730305,
  0.2551606,
  0.2665351,
  0.24893844,
  0.25469834,
  0.23863673,
  0.25839347,
  0.25119835,
  0.25500935,
  0.2297013,
  0.2614596],
 'model_s19': [0.1796475,
  0.16503727,
  0.18495712,
  0.17882058,
  0.17283073,
  0.15559746,
  0.17334783,
  0.1515295,
  0.14536925,
  0.14612211,
  0.1773133,
  0.18469653,
  0.17328113,
  0.17699693,
  0.1666071,
  0.17941035,
  0.17476296,
  0.1772418,
  0.16078284,
  0.1813813],
 'model_s20': [0.2695823,
  0.250749,
  0.27625808,
  0.26826856,
  0.26068664,
  0.23897123,
  0.26141122,
  0.23377694,
  0.22608104,
  0.22694185,
  0.26643255,
  0.27584356,
  0.26123664,
  0.2661466,
  0.25267416,
  0.26906493,
  0.2631654,
  0.26627597,
  0.24533774,
  0.27165842]}

In [81]:
resulting_df = pd.DataFrame(resultant_dataframe_to_be)

In [82]:
resulting_df

model_s1  model_s2  model_s3  model_s4  model_s5  model_s6  model_s7  \
0   0.268355  0.189734  0.284296  0.268423  0.239992  0.145910  0.237844   
1   0.239016  0.178411  0.251899  0.243347  0.214730  0.136832  0.216994   
2   0.278868  0.193768  0.296269  0.277851  0.249262  0.149323  0.245484   
3   0.266632  0.188966  0.282559  0.267221  0.238735  0.145478  0.236730   
4   0.254683  0.184396  0.269164  0.256742  0.228290  0.141686  0.228140   
5   0.219973  0.171311  0.231110  0.227078  0.198127  0.130921  0.203429   
6   0.255737  0.184828  0.270287  0.257572  0.229144  0.141986  0.228862   
7   0.211696  0.168191  0.222294  0.220254  0.191066  0.128434  0.197620   
8   0.199147  0.163560  0.208976  0.209878  0.180265  0.124643  0.188792   
9   0.200668  0.164082  0.210631  0.211211  0.181642  0.125129  0.189889   
10  0.263651  0.187854  0.279150  0.264513  0.236058  0.144499  0.234554   
11  0.278331  0.193529  0.295720  0.277439  0.248869  0.149173  0.245123   
12  0.255572  0.184723  0.270171  0.257580  0.229085  0.141991  0.228799   
13  0.263059  0.187671  0.278389  0.263828  0.235429  0.144247  0.234055   
14  0.242155  0.179571  0.255393  0.246130  0.217512  0.137843  0.219264   
15  0.267815  0.189441  0.283859  0.268231  0.239726  0.145845  0.237573   
16  0.258557  0.185889  0.273463  0.260067  0.231640  0.142888  0.230898   
17  0.263491  0.187766  0.279020  0.264438  0.235981  0.144471  0.234464   
18  0.230423  0.175150  0.242537  0.236095  0.207316  0.134200  0.210906   
19  0.271761  0.190998  0.288243  0.271597  0.243091  0.147061  0.240369   

    model_s8  model_s9  model_s10  model_s11  model_s12  model_s13  model_s14  \
0   0.110107  0.100831   0.076197   0.254099   0.290458   0.238594   0.253224   
1   0.102834  0.087187   0.073112   0.232240   0.271251   0.217602   0.233983   
2   0.112779  0.105990   0.077210   0.261847   0.297336   0.246143   0.260139   
3   0.109738  0.100280   0.075960   0.252631   0.289212   0.237344   0.252087   
4   0.106734  0.094540   0.074758   0.243810   0.281429   0.228784   0.244246   
5   0.098062  0.078051   0.071106   0.218464   0.259094   0.204084   0.221562   
6   0.106982  0.094966   0.074883   0.244639   0.282147   0.229540   0.244940   
7   0.096026  0.074233   0.070181   0.212416   0.253789   0.198222   0.216163   
8   0.092916  0.068337   0.068786   0.203404   0.245861   0.189378   0.207999   
9   0.093308  0.069125   0.068940   0.204434   0.246782   0.190442   0.208979   
10  0.108972  0.098778   0.075679   0.250475   0.287302   0.235209   0.250131   
11  0.112660  0.105779   0.077143   0.261395   0.296947   0.245749   0.259786   
12  0.106964  0.095027   0.074838   0.244447   0.281992   0.229428   0.244825   
13  0.108789  0.098339   0.075655   0.250132   0.286962   0.234790   0.249746   
14  0.103634  0.088765   0.073423   0.234492   0.273246   0.219841   0.236030   
15  0.110029  0.100828   0.076084   0.253534   0.290010   0.238197   0.252865   
16  0.107697  0.096344   0.075162   0.246693   0.283964   0.231555   0.246788   
17  0.108946  0.098754   0.075649   0.250313   0.287168   0.235089   0.250025   
18  0.100700  0.083173   0.072191   0.225933   0.265702   0.211494   0.228363   
19  0.110998  0.102616   0.076501   0.256530   0.292637   0.241034   0.255461   

    model_s15  model_s16  model_s17  model_s18  model_s19  model_s20  
0    0.213105   0.268891   0.241989   0.258832   0.179647   0.269582  
1    0.193738   0.241858   0.217694   0.236234   0.165037   0.250749  
2    0.220335   0.278837   0.250769   0.267001   0.184957   0.276258  
3    0.212127   0.267440   0.240481   0.257441   0.178821   0.268269  
4    0.204074   0.256284   0.230577   0.248224   0.172831   0.260687  
5    0.181223   0.224368   0.202298   0.221825   0.155597   0.238971  
6    0.204730   0.257220   0.231467   0.249047   0.173348   0.261411  
7    0.175939   0.216899   0.195623   0.215566   0.151530   0.233777  
8    0.167924   0.205569   0.185626   0.206202   0.145369   0.2260

In [83]:
resulting_df = pd.DataFrame(resulting_df)

In [84]:
resulting_df

model_s1  model_s2  model_s3  model_s4  model_s5  model_s6  model_s7  \
0   0.268355  0.189734  0.284296  0.268423  0.239992  0.145910  0.237844   
1   0.239016  0.178411  0.251899  0.243347  0.214730  0.136832  0.216994   
2   0.278868  0.193768  0.296269  0.277851  0.249262  0.149323  0.245484   
3   0.266632  0.188966  0.282559  0.267221  0.238735  0.145478  0.236730   
4   0.254683  0.184396  0.269164  0.256742  0.228290  0.141686  0.228140   
5   0.219973  0.171311  0.231110  0.227078  0.198127  0.130921  0.203429   
6   0.255737  0.184828  0.270287  0.257572  0.229144  0.141986  0.228862   
7   0.211696  0.168191  0.222294  0.220254  0.191066  0.128434  0.197620   
8   0.199147  0.163560  0.208976  0.209878  0.180265  0.124643  0.188792   
9   0.200668  0.164082  0.210631  0.211211  0.181642  0.125129  0.189889   
10  0.263651  0.187854  0.279150  0.264513  0.236058  0.144499  0.234554   
11  0.278331  0.193529  0.295720  0.277439  0.248869  0.149173  0.245123   
12  0.255572  0.184723  0.270171  0.257580  0.229085  0.141991  0.228799   
13  0.263059  0.187671  0.278389  0.263828  0.235429  0.144247  0.234055   
14  0.242155  0.179571  0.255393  0.246130  0.217512  0.137843  0.219264   
15  0.267815  0.189441  0.283859  0.268231  0.239726  0.145845  0.237573   
16  0.258557  0.185889  0.273463  0.260067  0.231640  0.142888  0.230898   
17  0.263491  0.187766  0.279020  0.264438  0.235981  0.144471  0.234464   
18  0.230423  0.175150  0.242537  0.236095  0.207316  0.134200  0.210906   
19  0.271761  0.190998  0.288243  0.271597  0.243091  0.147061  0.240369   

    model_s8  model_s9  model_s10  model_s11  model_s12  model_s13  model_s14  \
0   0.110107  0.100831   0.076197   0.254099   0.290458   0.238594   0.253224   
1   0.102834  0.087187   0.073112   0.232240   0.271251   0.217602   0.233983   
2   0.112779  0.105990   0.077210   0.261847   0.297336   0.246143   0.260139   
3   0.109738  0.100280   0.075960   0.252631   0.289212   0.237344   0.252087   
4   0.106734  0.094540   0.074758   0.243810   0.281429   0.228784   0.244246   
5   0.098062  0.078051   0.071106   0.218464   0.259094   0.204084   0.221562   
6   0.106982  0.094966   0.074883   0.244639   0.282147   0.229540   0.244940   
7   0.096026  0.074233   0.070181   0.212416   0.253789   0.198222   0.216163   
8   0.092916  0.068337   0.068786   0.203404   0.245861   0.189378   0.207999   
9   0.093308  0.069125   0.068940   0.204434   0.246782   0.190442   0.208979   
10  0.108972  0.098778   0.075679   0.250475   0.287302   0.235209   0.250131   
11  0.112660  0.105779   0.077143   0.261395   0.296947   0.245749   0.259786   
12  0.106964  0.095027   0.074838   0.244447   0.281992   0.229428   0.244825   
13  0.108789  0.098339   0.075655   0.250132   0.286962   0.234790   0.249746   
14  0.103634  0.088765   0.073423   0.234492   0.273246   0.219841   0.236030   
15  0.110029  0.100828   0.076084   0.253534   0.290010   0.238197   0.252865   
16  0.107697  0.096344   0.075162   0.246693   0.283964   0.231555   0.246788   
17  0.108946  0.098754   0.075649   0.250313   0.287168   0.235089   0.250025   
18  0.100700  0.083173   0.072191   0.225933   0.265702   0.211494   0.228363   
19  0.110998  0.102616   0.076501   0.256530   0.292637   0.241034   0.255461   

    model_s15  model_s16  model_s17  model_s18  model_s19  model_s20  
0    0.213105   0.268891   0.241989   0.258832   0.179647   0.269582  
1    0.193738   0.241858   0.217694   0.236234   0.165037   0.250749  
2    0.220335   0.278837   0.250769   0.267001   0.184957   0.276258  
3    0.212127   0.267440   0.240481   0.257441   0.178821   0.268269  
4    0.204074   0.256284   0.230577   0.248224   0.172831   0.260687  
5    0.181223   0.224368   0.202298   0.221825   0.155597   0.238971  
6    0.204730   0.257220   0.231467   0.249047   0.173348   0.261411  
7    0.175939   0.216899   0.195623   0.215566   0.151530   0.233777  
8    0.167924   0.205569   0.185626   0.206202   0.145369   0.2260

In [ ]:
resulting_df.to_csv('clustering_input.csv')

In [ ]:
resulting_df = scaler.inverse_transform(resulting_df)

In [ ]:
resulting_df

In [ ]:
resulting_df.to_csv('clustering_input.csv')

In [ ]:
df

In [85]:
for_clustering = scaler.inverse_transform(resulting_df)

In [87]:
for_clustering.to_csv('input_df_clustering.csv')