In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow.keras
from VectorNormalizer import VectorNormalizer

2022-03-14 17:56:45.510729: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-03-14 17:56:45.510764: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [2]:
df = pd.read_csv('_data.csv')

In [3]:
df.drop(columns=['timestep_time'], axis=1, inplace=True)

In [4]:
df.describe().T

count       mean       std  min    25%    50%    75%    max
vehicle_0   1369.0  13.304617  0.730812  0.0  13.01  13.34  13.68  14.00
vehicle_1   1369.0   8.840175  0.489463  0.0   8.53   8.85   9.17   9.52
vehicle_2   1369.0  14.572922  0.798959  0.0  14.29  14.63  14.94  15.27
vehicle_3   1369.0  13.307414  0.700379  0.0  13.01  13.36  13.67  14.00
vehicle_4   1369.0  11.320131  0.602395  0.0  11.02  11.34  11.67  12.00
vehicle_5   1369.0   6.515530  0.443259  0.0   6.20   6.52   6.85   7.18
vehicle_6   1369.0  11.320497  0.605771  0.0  11.02  11.34  11.68  12.00
vehicle_7   1369.0   4.696143  0.400734  0.0   4.38   4.70   5.03   5.35
vehicle_8   1369.0   3.460131  0.380911  0.0   3.14   3.46   3.77   4.12
vehicle_9   1369.0   3.428356  0.388740  0.0   3.11   3.42   3.77   4.08
vehicle_10  1369.0  12.319277  0.677380  0.0  12.03  12.35  12.69  13.00
vehicle_11  1369.0  14.688671  0.811304  0.0  14.41  14.75  15.05  15.38
vehicle_12  1369.0  11.339211  0.632542  0.0  11.04  11.38  11.70  12.00
vehicle_13  1369.0  12.320979  0.673965  0.0  12.01  12.35  12.69  13.00
vehicle_14  1369.0   9.781132  0.546465  0.0   9.46   9.81  10.14  10.45
vehicle_15  1369.0  13.317516  0.706316  0.0  13.03  13.35  13.68  14.00
vehicle_16  1369.0  11.479912  0.596174  0.0  11.19  11.52  11.83  12.13
vehicle_17  1369.0  12.652761  0.674286  0.0  12.37  12.68  13.02  13.33
vehicle_18  1369.0   8.010804  0.472543  0.0   7.69   8.01   8.36   8.68
vehicle_19  1369.0  13.324083  0.749694  0.0  13.04  13.36  13.69  14.00

In [5]:
df = df.iloc[1:, :]

In [6]:
df

vehicle_0  vehicle_1  vehicle_2  vehicle_3  vehicle_4  vehicle_5  \
1          1.44       2.60       1.75       2.34       2.03       1.43   
2          3.12       4.79       3.66       3.78       3.98       4.03   
3          5.66       6.47       5.75       6.23       6.54       6.21   
4          7.62       8.22       7.33       8.09       8.27       7.01   
5          9.45       8.63       8.92      10.40       9.69       6.62   
...         ...        ...        ...        ...        ...        ...   
1364      13.64       9.47      14.64      13.89      10.99       6.90   
1365      13.53       8.26      15.24      13.15      11.13       6.07   
1366      13.09       9.41      14.78      13.83      11.05       5.89   
1367      13.55       9.02      14.95      12.93      11.64       6.72   
1368      13.78       8.78      14.28      13.35      10.85       6.51   

      vehicle_6  vehicle_7  vehicle_8  vehicle_9  vehicle_10  vehicle_11  \
1          2.02       2.49       2.12       2.51        1.99        1.40   
2          3.85       4.36       3.96       3.63        3.48        3.44   
3          6.19       5.30       3.35       2.86        5.49        5.09   
4          8.71       4.96       3.63       3.87        6.97        7.23   
5         10.40       5.18       4.00       3.03        8.37        9.61   
...         ...        ...        ...        ...         ...         ...   
1364      11.63       4.43       2.91       3.42       12.10       14.19   
1365      10.81       4.87       3.92       3.09       11.89       14.27   
1366      11.36       5.05       3.13       3.16       12.07       15.25   
1367      11.64       4.41       3.51       3.72       12.91       15.34   
1368      11.75       4.68       3.81       3.69       11.93       14.94   

      vehicle_12  vehicle_13  vehicle_14  vehicle_15  vehicle_16  vehicle_17  \
1           1.34        1.71        2.01        1.96        2.20        1.38   
2           3.40        3.91        3.84        4.44        4.22        3.90   
3           5.00        5.36        5.37        5.83        6.80        6.25   
4           6.86        6.78        7.80        8.21        8.98        8.46   
5           9.39        9.35        9.24        9.65       10.92        9.82   
...          ...         ...         ...         ...         ...         ...   
1364       11.59       12.49        9.92       13.81       11.24       12.16   
1365       11.42       12.26        9.37       13.90       11.79       12.64   
1366       11.88       12.37       10.37       12.78       11.46       12.72   
1367       10.76       12.94        9.67       13.33       10.85       13.20   
1368       10.85       12.56        9.51       13.04       11.16       12.39   

      vehicle_18  vehicle_19  
1           2.32        1.36  
2           4.78        2.86  
3           6.51        4.32  
4           7.87        6.87  
5           7.76        8.93  
...          ...         ...  
1364        7.94       13.15  
1365        8.40       12.82  
1366        7.50       13.43  
1367        7.85       12.93  
1368        8.19       12.79  

[1368 rows x 20 columns]

In [7]:
scaler = VectorNormalizer()
scaler.fit(df)
df_scale_speed = scaler.transform(df)

In [8]:
df_scale_speed

0         1         2         3         4         5         6   \
0     0.163986  0.296085  0.199288  0.266477  0.231174  0.162847  0.230036   
1     0.178817  0.274530  0.209766  0.216644  0.228107  0.230972  0.220656   
2     0.225167  0.257390  0.228747  0.247843  0.260175  0.247047  0.246251   
3     0.232469  0.250774  0.223622  0.246808  0.252299  0.213859  0.265722   
4     0.242264  0.221242  0.228677  0.266619  0.248417  0.169713  0.266619   
...        ...       ...       ...       ...       ...       ...       ...   
1363  0.274796  0.190786  0.294942  0.279833  0.221408  0.139010  0.234302   
1364  0.274860  0.167801  0.309599  0.267141  0.226105  0.123311  0.219604   
1365  0.263185  0.189196  0.297164  0.278064  0.222169  0.118423  0.228402   
1366  0.271295  0.180596  0.299325  0.258881  0.233053  0.134546  0.233053   
1367  0.280843  0.178941  0.291034  0.272080  0.221128  0.132677  0.239471   

            7         8         9         10        11        12        13  \
0     0.283559  0.241423  0.285836  0.226619  0.159431  0.152598  0.194733   
1     0.249886  0.226960  0.208047  0.199450  0.197157  0.194865  0.224095   
2     0.210845  0.133270  0.113777  0.218404  0.202491  0.198911  0.213232   
3     0.151318  0.110743  0.118065  0.212639  0.220571  0.209283  0.206843   
4     0.132797  0.102546  0.077678  0.214577  0.246366  0.240726  0.239701   
...        ...       ...       ...       ...       ...       ...       ...   
1363  0.089248  0.058626  0.068900  0.243771  0.285876  0.233496  0.251628   
1364  0.098933  0.079634  0.062773  0.241544  0.289893  0.231996  0.249060   
1365  0.101534  0.062931  0.063534  0.242677  0.306614  0.238857  0.248709   
1366  0.088296  0.070276  0.074481  0.258481  0.307134  0.215434  0.259082   
1367  0.095381  0.077650  0.075204  0.243139  0.304485  0.221128  0.255979   

            14        15        16        17        18        19  
0     0.228897  0.223203  0.250534  0.157153  0.264199  0.154875  
1     0.220083  0.254471  0.241862  0.223522  0.273957  0.163916  
2     0.213630  0.231930  0.270518  0.248638  0.258982  0.171859  
3     0.237960  0.250469  0.273960  0.258096  0.240096  0.209588  
4     0.236881  0.247392  0.279950  0.251750  0.198939  0.228933  
...        ...       ...       ...       ...       ...       ...  
1363  0.199852  0.278221  0.226445  0.244979  0.159962  0.264924  
1364  0.190350  0.282377  0.239512  0.256780  0.170645  0.260437  
1365  0.208497  0.256952  0.230413  0.255746  0.150794  0.270021  
1366  0.193610  0.266890  0.217236  0.264287  0.157171  0.258881  
1367  0.193819  0.265762  0.227446  0.252514  0.166916  0.260667  

[1368 rows x 20 columns]

## Hardcode shit

In [9]:
car_1 = df_scale_speed.loc[:, 0]
car_2 = df_scale_speed.loc[:, 1]
car_3 = df_scale_speed.loc[:, 2]
car_4 = df_scale_speed.loc[:, 3]
car_5 = df_scale_speed.loc[:, 4]
car_6 = df_scale_speed.loc[:, 5]
car_7 = df_scale_speed.loc[:, 6]
car_8 = df_scale_speed.loc[:, 7]
car_9 = df_scale_speed.loc[:, 8]
car_10 = df_scale_speed.loc[:, 9]
car_11 = df_scale_speed.loc[:, 10]
car_12 = df_scale_speed.loc[:, 11]
car_13 = df_scale_speed.loc[:, 12]
car_14 = df_scale_speed.loc[:, 13]
car_15 = df_scale_speed.loc[:, 14]
car_16 = df_scale_speed.loc[:, 15]
car_17 = df_scale_speed.loc[:, 16]
car_18 = df_scale_speed.loc[:, 17]
car_19 = df_scale_speed.loc[:, 18]
car_20 = df_scale_speed.loc[:, 19]

In [10]:
# splitting train - test data

train_car1 = car_1.iloc[:1200]
test_car1 = car_1.iloc[1200:]

train_car2 = car_2.iloc[:1200]
test_car2 = car_2.iloc[1200:]

train_car3 = car_3.iloc[:1200]
test_car3 = car_3.iloc[1200:]

train_car4 = car_4.iloc[:1200]
test_car4 = car_4.iloc[1200:]

train_car5 = car_5.iloc[:1200]
test_car5 = car_5.iloc[1200:]

train_car6 = car_6.iloc[:1200]
test_car6 = car_6.iloc[1200:]

train_car7 = car_7.iloc[:1200]
test_car7 = car_7.iloc[1200:]

train_car8 = car_8.iloc[:1200]
test_car8 = car_8.iloc[1200:]

train_car9 = car_9.iloc[:1200]
test_car9 = car_9.iloc[1200:]

train_car10 = car_10.iloc[:1200]
test_car10 = car_10.iloc[1200:]

train_car11 = car_11.iloc[:1200]
test_car11 = car_11.iloc[1200:]

train_car12 = car_12.iloc[:1200]
test_car12 = car_12.iloc[1200:]

train_car13 = car_13.iloc[:1200]
test_car13= car_13.iloc[1200:]

train_car14 = car_14.iloc[:1200]
test_car14 = car_14.iloc[1200:]

train_car14 = car_14.iloc[:1200]
test_car14 = car_14.iloc[1200:]

train_car15 = car_15.iloc[:1200]
test_car15 = car_15.iloc[1200:]

train_car16 = car_16.iloc[:1200]
test_car16 = car_16.iloc[1200:]

train_car17 = car_17.iloc[:1200]
test_car17 = car_17.iloc[1200:]

train_car18 = car_18.iloc[:1200]
test_car18 = car_18.iloc[1200:]

train_car19 = car_19.iloc[:1200]
test_car19 = car_19.iloc[1200:]

train_car20 = car_20.iloc[:1200]
test_car20 = car_20.iloc[1200:]

In [11]:
from utils import create_dataset

In [12]:
TIME_STEPS = 4

train_features_speed1, train_labels_speed1 = create_dataset(train_car1.to_numpy(), TIME_STEPS)
test_features_speed1, test_labels_speed1 = create_dataset(test_car1.to_numpy(), TIME_STEPS)

train_features_speed2, train_labels_speed2 = create_dataset(train_car2.to_numpy(), TIME_STEPS)
test_features_speed2, test_labels_speed2 = create_dataset(test_car2.to_numpy(), TIME_STEPS)

train_features_speed3, train_labels_speed3 = create_dataset(train_car3.to_numpy(), TIME_STEPS)
test_features_speed3, test_labels_speed3 = create_dataset(test_car3.to_numpy(), TIME_STEPS)

train_features_speed4, train_labels_speed4 = create_dataset(train_car4.to_numpy(), TIME_STEPS)
test_features_speed4, test_labels_speed4 = create_dataset(test_car4.to_numpy(), TIME_STEPS)

train_features_speed5, train_labels_speed5 = create_dataset(train_car5.to_numpy(), TIME_STEPS)
test_features_speed5, test_labels_speed5 = create_dataset(test_car5.to_numpy(), TIME_STEPS)

train_features_speed6, train_labels_speed6 = create_dataset(train_car6.to_numpy(), TIME_STEPS)
test_features_speed6, test_labels_speed6 = create_dataset(test_car6.to_numpy(), TIME_STEPS)

train_features_speed7, train_labels_speed7 = create_dataset(train_car7.to_numpy(), TIME_STEPS)
test_features_speed7, test_labels_speed7 = create_dataset(test_car7.to_numpy(), TIME_STEPS)

train_features_speed8, train_labels_speed8 = create_dataset(train_car8.to_numpy(), TIME_STEPS)
test_features_speed8, test_labels_speed8 = create_dataset(test_car8.to_numpy(), TIME_STEPS)

train_features_speed9, train_labels_speed9 = create_dataset(train_car9.to_numpy(), TIME_STEPS)
test_features_speed9, test_labels_speed9 = create_dataset(test_car9.to_numpy(), TIME_STEPS)

train_features_speed10, train_labels_speed10 = create_dataset(train_car10.to_numpy(), TIME_STEPS)
test_features_speed10, test_labels_speed10 = create_dataset(test_car10.to_numpy(), TIME_STEPS)

train_features_speed11, train_labels_speed11 = create_dataset(train_car11.to_numpy(), TIME_STEPS)
test_features_speed11, test_labels_speed11 = create_dataset(test_car11.to_numpy(), TIME_STEPS)

train_features_speed12, train_labels_speed12 = create_dataset(train_car12.to_numpy(), TIME_STEPS)
test_features_speed12, test_labels_speed12 = create_dataset(test_car12.to_numpy(), TIME_STEPS)

train_features_speed13, train_labels_speed13 = create_dataset(train_car13.to_numpy(), TIME_STEPS)
test_features_speed13, test_labels_speed13 = create_dataset(test_car13.to_numpy(), TIME_STEPS)

train_features_speed14, train_labels_speed14 = create_dataset(train_car14.to_numpy(), TIME_STEPS)
test_features_speed14, test_labels_speed14 = create_dataset(test_car14.to_numpy(), TIME_STEPS)

train_features_speed15, train_labels_speed15 = create_dataset(train_car15.to_numpy(), TIME_STEPS)
test_features_speed15, test_labels_speed15 = create_dataset(test_car15.to_numpy(), TIME_STEPS)

train_features_speed16, train_labels_speed16 = create_dataset(train_car16.to_numpy(), TIME_STEPS)
test_features_speed16, test_labels_speed16 = create_dataset(test_car16.to_numpy(), TIME_STEPS)

train_features_speed17, train_labels_speed17 = create_dataset(train_car17.to_numpy(), TIME_STEPS)
test_features_speed17, test_labels_speed17 = create_dataset(test_car17.to_numpy(), TIME_STEPS)

train_features_speed18, train_labels_speed18 = create_dataset(train_car18.to_numpy(), TIME_STEPS)
test_features_speed18, test_labels_speed18 = create_dataset(test_car18.to_numpy(), TIME_STEPS)

train_features_speed19, train_labels_speed19 = create_dataset(train_car19.to_numpy(), TIME_STEPS)
test_features_speed19, test_labels_speed19 = create_dataset(test_car19.to_numpy(), TIME_STEPS)

train_features_speed20, train_labels_speed20 = create_dataset(train_car20.to_numpy(), TIME_STEPS)
test_features_speed20, test_labels_speed20 = create_dataset(test_car20.to_numpy(), TIME_STEPS)

In [13]:
print(train_features_speed20.shape)
print(test_features_speed20.shape)
print(train_labels_speed20.shape)
print(test_labels_speed20.shape)

(1196, 4)
(164, 4)
(1196,)
(164,)


In [15]:
train_features_speed1 = train_features_speed1.reshape(1196, 4,1)
test_features_speed1 = test_features_speed1.reshape(164, 4,1)

train_features_speed2 = train_features_speed2.reshape(1196, 4,1)
test_features_speed2 = test_features_speed2.reshape(164, 4,1)

train_features_speed3 = train_features_speed3.reshape(1196, 4,1)
test_features_speed3 = test_features_speed3.reshape(164, 4,1)

train_features_speed4 = train_features_speed4.reshape(1196, 4,1)
test_features_speed4 = test_features_speed4.reshape(164, 4,1)

train_features_speed5 = train_features_speed5.reshape(1196, 4,1)
test_features_speed5 = test_features_speed5.reshape(164, 4,1)

train_features_speed6 = train_features_speed6.reshape(1196, 4,1)
test_features_speed6 = test_features_speed6.reshape(164, 4,1)

train_features_speed7 = train_features_speed7.reshape(1196, 4,1)
test_features_speed7 = test_features_speed7.reshape(164, 4,1)

train_features_speed8 = train_features_speed8.reshape(1196, 4,1)
test_features_speed8 = test_features_speed8.reshape(164, 4,1)

train_features_speed9 = train_features_speed9.reshape(1196, 4,1)
test_features_speed9 = test_features_speed9.reshape(164, 4,1)

train_features_speed10 = train_features_speed10.reshape(1196, 4,1)
test_features_speed10 = test_features_speed10.reshape(164, 4,1)

train_features_speed11 = train_features_speed11.reshape(1196, 4,1)
test_features_speed11 = test_features_speed11.reshape(164, 4,1)

train_features_speed12 = train_features_speed12.reshape(1196, 4,1)
test_features_speed12 = test_features_speed12.reshape(164, 4,1)

train_features_speed13 = train_features_speed13.reshape(1196, 4,1)
test_features_speed13 = test_features_speed13.reshape(164, 4,1)

train_features_speed14 = train_features_speed14.reshape(1196, 4,1)
test_features_speed14 = test_features_speed14.reshape(164, 4,1)

train_features_speed15 = train_features_speed15.reshape(1196, 4,1)
test_features_speed15 = test_features_speed15.reshape(164, 4,1)

train_features_speed16 = train_features_speed16.reshape(1196, 4,1)
test_features_speed16 = test_features_speed16.reshape(164, 4,1)

train_features_speed17 = train_features_speed17.reshape(1196, 4,1)
test_features_speed17 = test_features_speed17.reshape(164, 4,1)

train_features_speed18 = train_features_speed18.reshape(1196, 4,1)
test_features_speed18 = test_features_speed18.reshape(164, 4,1)

train_features_speed19 = train_features_speed19.reshape(1196, 4,1)
test_features_speed19 = test_features_speed19.reshape(164, 4,1)

train_features_speed20 = train_features_speed20.reshape(1196, 4,1)
test_features_speed20 = test_features_speed20.reshape(164, 4,1)

In [22]:
def build_model():
    model = tensorflow.keras.models.Sequential()
    model.add(tensorflow.keras.layers.LSTM(18, input_shape=(4,1),return_sequences=True))
    model.add(tensorflow.keras.layers.LSTM(9))
    model.add(tensorflow.keras.layers.Dense(1))

    model.compile(optimizer = 'adam', loss = ['mse'])
    
    return model

In [17]:
from collections import OrderedDict

all_vehicles = OrderedDict()

for i in range(1, 21):
    all_vehicles[f'model_s{i}'] = None

In [18]:
all_vehicles

OrderedDict([('model_s1', None),
             ('model_s2', None),
             ('model_s3', None),
             ('model_s4', None),
             ('model_s5', None),
             ('model_s6', None),
             ('model_s7', None),
             ('model_s8', None),
             ('model_s9', None),
             ('model_s10', None),
             ('model_s11', None),
             ('model_s12', None),
             ('model_s13', None),
             ('model_s14', None),
             ('model_s15', None),
             ('model_s16', None),
             ('model_s17', None),
             ('model_s18', None),
             ('model_s19', None),
             ('model_s20', None)])

In [35]:
for vehicle_name in all_vehicles.keys():
    all_vehicles[vehicle_name] = build_model()

In [24]:
all_vehicles

OrderedDict([('model_s1',
              <keras.engine.sequential.Sequential at 0x7f2facc9df40>),
             ('model_s2',
              <keras.engine.sequential.Sequential at 0x7f2fa8214040>),
             ('model_s3',
              <keras.engine.sequential.Sequential at 0x7f2fa81955b0>),
             ('model_s4',
              <keras.engine.sequential.Sequential at 0x7f2f8c7f3b80>),
             ('model_s5',
              <keras.engine.sequential.Sequential at 0x7f2fa814c760>),
             ('model_s6',
              <keras.engine.sequential.Sequential at 0x7f2fa803bd30>),
             ('model_s7',
              <keras.engine.sequential.Sequential at 0x7f2fa82059a0>),
             ('model_s8',
              <keras.engine.sequential.Sequential at 0x7f2f8c729d90>),
             ('model_s9',
              <keras.engine.sequential.Sequential at 0x7f2f8c6cb820>),
             ('model_s10',
              <keras.engine.sequential.Sequential at 0x7f2f8c5abfa0>),
             ('model_s11',
  

In [25]:
train_features = [
                    train_features_speed1,
                    train_features_speed2,
                    train_features_speed3,
                    train_features_speed4,
                    train_features_speed5,
                    train_features_speed6,
                    train_features_speed7,
                    train_features_speed8,
                    train_features_speed9,
                    train_features_speed10,
                    train_features_speed11,
                    train_features_speed12,
                    train_features_speed13,
                    train_features_speed14,
                    train_features_speed15,
                    train_features_speed16,
                    train_features_speed17,
                    train_features_speed18,
                    train_features_speed19,
                    train_features_speed20
]

In [26]:
train_labels = [
                train_labels_speed1,
                train_labels_speed2,
                train_labels_speed3,
                train_labels_speed4,
                train_labels_speed5,
                train_labels_speed6,
                train_labels_speed7,
                train_labels_speed8,
                train_labels_speed9,
                train_labels_speed10,
                train_labels_speed11,
                train_labels_speed12,
                train_labels_speed13,
                train_labels_speed14,
                train_labels_speed15,
                train_labels_speed16,
                train_labels_speed17,
                train_labels_speed18,
                train_labels_speed19,
                train_labels_speed20,
]

In [27]:
test_features = [
                    test_features_speed1,
                    test_features_speed2,
                    test_features_speed3,
                    test_features_speed4,
                    test_features_speed5,
                    test_features_speed6,
                    test_features_speed7,
                    test_features_speed8,
                    test_features_speed9,
                    test_features_speed10,
                    test_features_speed11,
                    test_features_speed12,
                    test_features_speed13,
                    test_features_speed14,
                    test_features_speed15,
                    test_features_speed16,
                    test_features_speed17,
                    test_features_speed18,
                    test_features_speed19,
                    test_features_speed20,
]

In [28]:
test_labels = [
                test_labels_speed1,
                test_labels_speed2,
                test_labels_speed3,
                test_labels_speed4,
                test_labels_speed5,
                test_labels_speed6,
                test_labels_speed7,
                test_labels_speed8,
                test_labels_speed9,
                test_labels_speed10,
                test_labels_speed11,
                test_labels_speed12,
                test_labels_speed13,
                test_labels_speed14,
                test_labels_speed15,
                test_labels_speed16,
                test_labels_speed17,
                test_labels_speed18,
                test_labels_speed19,
                test_labels_speed20
]

In [29]:
train_features

[array([[[0.16398571],
         [0.17881723],
         [0.22516687],
         [0.23246903]],
 
        [[0.17881723],
         [0.22516687],
         [0.23246903],
         [0.24226432]],
 
        [[0.22516687],
         [0.23246903],
         [0.24226432],
         [0.26475597]],
 
        ...,
 
        [[0.28304908],
         [0.25700868],
         [0.26701658],
         [0.26800389]],
 
        [[0.25700868],
         [0.26701658],
         [0.26800389],
         [0.26389525]],
 
        [[0.26701658],
         [0.26800389],
         [0.26389525],
         [0.25692183]]]),
 array([[[0.29608532],
         [0.2745303 ],
         [0.2573904 ],
         [0.25077368]],
 
        [[0.2745303 ],
         [0.2573904 ],
         [0.25077368],
         [0.22124245]],
 
        [[0.2573904 ],
         [0.25077368],
         [0.22124245],
         [0.18305479]],
 
        ...,
 
        [[0.19248962],
         [0.1847313 ],
         [0.17429122],
         [0.18986153]],
 
        [[0.1847313 

In [34]:
all_veh_hists = []

In [36]:
for i, vehicle_name in enumerate(all_vehicles.keys()):
    model = all_vehicles[vehicle_name]
    history = model.fit(
        train_features[i],
        train_labels[i], 
        batch_size = 64, 
        epochs = 50, 
        shuffle = False, 
        validation_split = .15
    )
    all_veh_hists.append({vehicle_name : history})

Epoch 1/50
16/16 [==============================] - 5s 72ms/step - loss: 0.0511 - val_loss: 0.0309
Epoch 2/50
16/16 [==============================] - 0s 8ms/step - loss: 0.0164 - val_loss: 0.0036
Epoch 3/50
16/16 [==============================] - 0s 8ms/step - loss: 9.4648e-04 - val_loss: 9.3252e-04
Epoch 4/50
16/16 [==============================] - 0s 8ms/step - loss: 4.9978e-04 - val_loss: 5.5122e-05
Epoch 5/50
16/16 [==============================] - ETA: 0s - loss: 9.4836e-0 - 0s 8ms/step - loss: 1.0481e-04 - val_loss: 9.4347e-05
Epoch 6/50
16/16 [==============================] - 0s 8ms/step - loss: 6.7454e-05 - val_loss: 5.8426e-05
Epoch 7/50
16/16 [==============================] - 0s 8ms/step - loss: 5.9400e-05 - val_loss: 5.4728e-05
Epoch 8/50
16/16 [==============================] - 0s 8ms/step - loss: 5.7556e-05 - val_loss: 5.4497e-05
Epoch 9/50
16/16 [==============================] - 0s 8ms/step - loss: 5.7243e-05 - val_loss: 5.4023e-05
Epoch 10/50
16/16 [==============

[0.05105956643819809,
 0.016430752351880074,
 0.0009464802569709718,
 0.0004997775540687144,
 0.00010480589116923511,
 6.745414430042729e-05,
 5.9400372265372425e-05,
 5.7555545936338603e-05,
 5.7243330957135186e-05,
 5.699026951333508e-05,
 5.7109999033855274e-05,
 5.705682633561082e-05,
 5.707459422410466e-05,
 5.7072284107562155e-05,
 5.707400487153791e-05,
 5.707594391424209e-05,
 5.707704258384183e-05,
 5.7078676036326215e-05,
 5.707996751880273e-05,
 5.708138269255869e-05,
 5.70827214687597e-05,
 5.708402022719383e-05,
 5.708535172743723e-05,
 5.7086632295977324e-05,
 5.7087909226538613e-05,
 5.7089171605184674e-05,
 5.709043762180954e-05,
 5.709166725864634e-05,
 5.709290417144075e-05,
 5.7094137446256354e-05,
 5.709537799702957e-05,
 5.7096600357908756e-05,
 5.709783363272436e-05,
 5.709905963158235e-05,
 5.710030745831318e-05,
 5.710154437110759e-05,
 5.7102792197838426e-05,
 5.710406549042091e-05,
 5.710530967917293e-05,
 5.7106608437607065e-05,
 5.7107896282104775e-05,
 5.71

In [45]:
# predictions
all_predictions = []

for i, vehicle_name in enumerate(all_vehicles.keys()):
    model = all_vehicles[vehicle_name]
    preds = model.predict(test_features[i])
    all_predictions.append({vehicle_name : preds})

In [46]:
all_predictions


[{'model_s1': array([[0.26688275],
         [0.26718217],
         [0.26801187],
         [0.26848796],
         [0.26839945],
         [0.26800388],
         [0.26777458],
         [0.26800472],
         [0.26846367],
         [0.26982042],
         [0.269024  ],
         [0.26771763],
         [0.26805365],
         [0.2684698 ],
         [0.2685915 ],
         [0.26894858],
         [0.26741242],
         [0.26918018],
         [0.2694683 ],
         [0.27049237],
         [0.27167627],
         [0.2710085 ],
         [0.27049977],
         [0.269459  ],
         [0.2690526 ],
         [0.2681158 ],
         [0.2687607 ],
         [0.26912993],
         [0.2682932 ],
         [0.2675408 ],
         [0.26805496],
         [0.26901183],
         [0.26861525],
         [0.26773036],
         [0.26821965],
         [0.26830295],
         [0.26882577],
         [0.26801664],
         [0.26805487],
         [0.2691519 ],
         [0.2688284 ],
         [0.26954386],
         [0.26978934],

In [47]:
test_features

[array([[[0.26168265],
         [0.25818766],
         [0.26279173],
         [0.26782105]],
 
        [[0.25818766],
         [0.26279173],
         [0.26782105],
         [0.26632546]],
 
        [[0.26279173],
         [0.26782105],
         [0.26632546],
         [0.2686336 ]],
 
        [[0.26782105],
         [0.26632546],
         [0.2686336 ],
         [0.26811149]],
 
        [[0.26632546],
         [0.2686336 ],
         [0.26811149],
         [0.26517961]],
 
        [[0.2686336 ],
         [0.26811149],
         [0.26517961],
         [0.25399104]],
 
        [[0.26811149],
         [0.26517961],
         [0.25399104],
         [0.2752721 ]],
 
        [[0.26517961],
         [0.25399104],
         [0.2752721 ],
         [0.27834271]],
 
        [[0.25399104],
         [0.2752721 ],
         [0.27834271],
         [0.26695911]],
 
        [[0.2752721 ],
         [0.27834271],
         [0.26695911],
         [0.26125258]],
 
        [[0.27834271],
         [0.26695911],
    

In [48]:
test_labels

[array([0.26632546, 0.2686336 , 0.26811149, 0.26517961, 0.25399104,
        0.2752721 , 0.27834271, 0.26695911, 0.26125258, 0.26657515,
        0.26375124, 0.2813927 , 0.25453447, 0.27190895, 0.26628769,
        0.26434431, 0.28452071, 0.27701627, 0.27798092, 0.27312487,
        0.28054622, 0.26162525, 0.26096348, 0.27432174, 0.27661314,
        0.26188596, 0.2569725 , 0.26959021, 0.27700402, 0.26272661,
        0.26396655, 0.26352743, 0.27459396, 0.26685063, 0.25837119,
        0.27631887, 0.26218461, 0.26937564, 0.27249355, 0.27921676,
        0.26127546, 0.27580824, 0.27716318, 0.26186056, 0.25947179,
        0.27494049, 0.2735853 , 0.26150012, 0.25822203, 0.26493939,
        0.27139488, 0.27289082, 0.26879976, 0.26179916, 0.2553693 ,
        0.25592932, 0.26492653, 0.27808977, 0.27332279, 0.26275665,
        0.27341048, 0.27250304, 0.26906061, 0.27350074, 0.27451602,
        0.27239434, 0.28090579, 0.26606726, 0.26448141, 0.25970287,
        0.26928427, 0.26463222, 0.27248964, 0.27

In [52]:
len(test_features_speed1)

164

In [65]:
all_veh_windows = []

for feature in test_features:
    x = feature[-1:]
    all_veh_windows.append(x)

In [92]:
np.array(all_veh_windows).shape

(20, 1, 4, 1)

In [ ]:
all_

In [87]:
# all_veh_windows
for car in all_veh_windows:
    print(car.shape)
    print(type(car))

(1, 4, 1)
<class 'numpy.ndarray'>
(1, 4, 1)
<class 'numpy.ndarray'>
(1, 4, 1)
<class 'numpy.ndarray'>
(1, 4, 1)
<class 'numpy.ndarray'>
(1, 4, 1)
<class 'numpy.ndarray'>
(1, 4, 1)
<class 'numpy.ndarray'>
(1, 4, 1)
<class 'numpy.ndarray'>
(1, 4, 1)
<class 'numpy.ndarray'>
(1, 4, 1)
<class 'numpy.ndarray'>
(1, 4, 1)
<class 'numpy.ndarray'>
(1, 4, 1)
<class 'numpy.ndarray'>
(1, 4, 1)
<class 'numpy.ndarray'>
(1, 4, 1)
<class 'numpy.ndarray'>
(1, 4, 1)
<class 'numpy.ndarray'>
(1, 4, 1)
<class 'numpy.ndarray'>
(1, 4, 1)
<class 'numpy.ndarray'>
(1, 4, 1)
<class 'numpy.ndarray'>
(1, 4, 1)
<class 'numpy.ndarray'>
(1, 4, 1)
<class 'numpy.ndarray'>
(1, 4, 1)
<class 'numpy.ndarray'>


In [70]:
placeholder = np.array(all_veh_windows).reshape

In [71]:
placeholder.shape

(20, 4, 1)

In [78]:
names = list(all_vehicles.keys())

In [88]:
names

['model_s1',
 'model_s2',
 'model_s3',
 'model_s4',
 'model_s5',
 'model_s6',
 'model_s7',
 'model_s8',
 'model_s9',
 'model_s10',
 'model_s11',
 'model_s12',
 'model_s13',
 'model_s14',
 'model_s15',
 'model_s16',
 'model_s17',
 'model_s18',
 'model_s19',
 'model_s20']

In [89]:
all_speed_windows = {car: [] for car in names}

In [90]:
all_speed_windows

{'model_s1': [],
 'model_s2': [],
 'model_s3': [],
 'model_s4': [],
 'model_s5': [],
 'model_s6': [],
 'model_s7': [],
 'model_s8': [],
 'model_s9': [],
 'model_s10': [],
 'model_s11': [],
 'model_s12': [],
 'model_s13': [],
 'model_s14': [],
 'model_s15': [],
 'model_s16': [],
 'model_s17': [],
 'model_s18': [],
 'model_s19': [],
 'model_s20': []}

In [ ]:
all

In [146]:
reyan_ka_keera = np.array(all_veh_windows).tolist()

In [148]:
len(reyan_ka_keera)

20

In [152]:
reyan_ka_keera[0]

[[[0.27479596365664594],
  [0.27486037631511645],
  [0.26318528426741605],
  [0.27129494398750853]]]

In [153]:
type(reyan_ka_keera[0])

list

In [154]:
reyan_ka_keera[0][0]

[[0.27479596365664594],
 [0.27486037631511645],
 [0.26318528426741605],
 [0.27129494398750853]]

[[0.27479596365664594], [0.27486037631511645], [0.26318528426741605], [0.27129494398750853]]
##########################################################################################
[[0.1907857606912344], [0.1678009392729388], [0.18919583842294768], [0.1805963390972197]]
##########################################################################################
[[0.2949422953030276], [0.30959882742367884], [0.2971641330383812], [0.2993254179050371]]
##########################################################################################
[[0.27983254656824136], [0.2671407205132137], [0.27806359674701026], [0.2588814483954602]]
##########################################################################################
[[0.22140818479373453], [0.22610465546099381], [0.22216939581015643], [0.23305336885716602]]
##########################################################################################
[[0.13900968836003352], [0.12331134399355187], [0.11842332500649966], [0.134546274804137

In [141]:
temp = np.array([])
for val in np.array(all_veh_windows):
    np.append(temp, val.reshape(1,4))

print(temp)
print(type(temp))
print(np.array(temp).shape)

# temp.tolist()

[]
<class 'numpy.ndarray'>
(0,)


In [122]:
for i, individual_window in enumerate(all_veh_windows):
    # print(type(individual_window[0]))
    # speed
    for value in individual_window:
        all_speed_windows[names[i]].append(list(value))
        print(type(list(value)))

<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>
<class 'list'>


In [123]:
all_speed_windows['model_s1']

[array([[0.27479596],
        [0.27486038],
        [0.26318528],
        [0.27129494]]),
 [array([0.27479596]),
  array([0.27486038]),
  array([0.26318528]),
  array([0.27129494])],
 [array([0.27479596]),
  array([0.27486038]),
  array([0.26318528]),
  array([0.27129494])],
 [array([0.27479596]),
  array([0.27486038]),
  array([0.26318528]),
  array([0.27129494])],
 [array([0.27479596]),
  array([0.27486038]),
  array([0.26318528]),
  array([0.27129494])],
 [array([0.27479596]),
  array([0.27486038]),
  array([0.26318528]),
  array([0.27129494])],
 0.27479596365664594,
 0.27479596365664594,
 array([0.27479596]),
 array([0.27486038]),
 array([0.26318528]),
 array([0.27129494]),
 array([0.27479596]),
 array([0.27486038]),
 array([0.26318528]),
 array([0.27129494]),
 [0.27479596365664594],
 [0.27486037631511645],
 [0.26318528426741605],
 [0.27129494398750853],
 [0.27479596365664594],
 [0.27486037631511645],
 [0.26318528426741605],
 [0.27129494398750853],
 [array([0.27479596]),
  array([0

In [120]:
all_speed_windows

{'model_s1': [array([[0.27479596],
         [0.27486038],
         [0.26318528],
         [0.27129494]]),
  [array([0.27479596]),
   array([0.27486038]),
   array([0.26318528]),
   array([0.27129494])],
  [array([0.27479596]),
   array([0.27486038]),
   array([0.26318528]),
   array([0.27129494])],
  [array([0.27479596]),
   array([0.27486038]),
   array([0.26318528]),
   array([0.27129494])],
  [array([0.27479596]),
   array([0.27486038]),
   array([0.26318528]),
   array([0.27129494])],
  [array([0.27479596]),
   array([0.27486038]),
   array([0.26318528]),
   array([0.27129494])],
  0.27479596365664594,
  0.27479596365664594,
  array([0.27479596]),
  array([0.27486038]),
  array([0.26318528]),
  array([0.27129494]),
  array([0.27479596]),
  array([0.27486038]),
  array([0.26318528]),
  array([0.27129494]),
  [0.27479596365664594],
  [0.27486037631511645],
  [0.26318528426741605],
  [0.27129494398750853]],
 'model_s2': [array([[0.19078576],
         [0.16780094],
         [0.18919584

In [74]:
#position
out_append_pos=[]
for i in range(40):
    temp=np.array(s_list).reshape(1,4,17)
    pred=model_p.predict(temp)
    # print(pred[0])
    out_append_pos.append(list(pred[0]))
    p_list.append(list(pred[0]))
    p_list.pop(0)

array([[0.26492426],
       [0.26043681],
       [0.27002127],
       [0.25888145]])

array([[[0.27479596],
        [0.27486038],
        [0.26318528],
        [0.27129494]],

       [[0.19078576],
        [0.16780094],
        [0.18919584],
        [0.18059634]],

       [[0.2949423 ],
        [0.30959883],
        [0.29716413],
        [0.29932542]],

       [[0.27983255],
        [0.26714072],
        [0.2780636 ],
        [0.25888145]],

       [[0.22140818],
        [0.22610466],
        [0.2221694 ],
        [0.23305337]],

       [[0.13900969],
        [0.12331134],
        [0.11842333],
        [0.13454627]],

       [[0.23430184],
        [0.21960389],
        [0.2284022 ],
        [0.23305337]],

       [[0.08924825],
        [0.09893348],
        [0.10153443],
        [0.08829599]],

       [[0.05862583],
        [0.07963434],
        [0.06293124],
        [0.0702764 ]],

       [[0.06890045],
        [0.06277299],
        [0.06353442],
        [0.07448097]],

       [[0.24377061],
        [0.24154397],
        [0.24267734],
        [0.25848101]],

       [[0